### ISSUE TITLE
build error 1.0.45 (beta)

### ISSUE THREAD

**Issue by toptim** [hyle-team/zano#106]
ubuntu 16
cmake version 3.12.0
boost 1.70
build from [https://github.com/hyle-team/zano/archive/v1.0.45.tar.gz](url)

`make -j$(nproc)
mkdir -p build/release && cd build/release && cmake  -D CMAKE_BUILD_TYPE=Release ../../ && make
CMake Deprecation Warning at CMakeLists.txt:9 (cmake_policy):
  The OLD behavior for policy CMP0043 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

CMake Deprecation Warning at CMakeLists.txt:13 (cmake_policy):
  The OLD behavior for policy CMP0020 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

Generated with config types: , and built type: Release
-- Found Boost 1.70.0 at /usr/local/lib/cmake/Boost-1.70.0
--   Requested configuration: QUIET REQUIRED COMPONENTS system;filesystem;thread;timer;date_time;chrono;regex;serialization;atomic;program_options;locale
-- Found boost_headers 1.70.0 at /usr/local/lib/cmake/boost_headers-1.70.0
-- Found boost_system 1.70.0 at /usr/local/lib/cmake/boost_system-1.70.0
--   libboost_system.a
-- Adding boost_system dependencies: headers
-- Found boost_filesystem 1.70.0 at /usr/local/lib/cmake/boost_filesystem-1.70.0
--   libboost_filesystem.a
-- Adding boost_filesystem dependencies: headers
-- Found boost_thread 1.70.0 at /usr/local/lib/cmake/boost_thread-1.70.0
--   libboost_thread.a
-- Adding boost_thread dependencies: headers
-- Found boost_timer 1.70.0 at /usr/local/lib/cmake/boost_timer-1.70.0
--   libboost_timer.a
-- Adding boost_timer dependencies: chrono;headers
-- Found boost_chrono 1.70.0 at /usr/local/lib/cmake/boost_chrono-1.70.0
--   libboost_chrono.a
-- Adding boost_chrono dependencies: headers
-- Found boost_date_time 1.70.0 at /usr/local/lib/cmake/boost_date_time-1.70.0
--   libboost_date_time.a
-- Adding boost_date_time dependencies: headers
-- Found boost_regex 1.70.0 at /usr/local/lib/cmake/boost_regex-1.70.0
--   libboost_regex.a
-- Adding boost_regex dependencies: headers
-- Found boost_serialization 1.70.0 at /usr/local/lib/cmake/boost_serialization-1.70.0
--   libboost_serialization.a
-- Adding boost_serialization dependencies: headers
-- Found boost_atomic 1.70.0 at /usr/local/lib/cmake/boost_atomic-1.70.0
--   libboost_atomic.a
-- Adding boost_atomic dependencies: headers
-- Found boost_program_options 1.70.0 at /usr/local/lib/cmake/boost_program_options-1.70.0
--   libboost_program_options.a
-- Adding boost_program_options dependencies: headers
-- Found boost_locale 1.70.0 at /usr/local/lib/cmake/boost_locale-1.70.0
--   libboost_locale.a
-- Adding boost_locale dependencies: chrono;system;thread;headers
-- Boost 1.53 found.
-- Found Boost components:
   system;filesystem;thread;timer;date_time;chrono;regex;serialization;atomic;program_options;locale
CMake Error at CMakeLists.txt:164 (if):
  if given arguments:

    "MSVC" "AND" "(" "EQUAL" "1" ")" "AND" "(" "EQUAL" "54" ")"

  Unknown arguments specified
`

**Comment by toptim** [comment]
1.0.54 (beta 2, release candidate) build same error

**Comment by toptim** [comment]
upgrade to ubuntu 18 help me to run release build

**Comment by cryptozoidberg** [comment]
@toptim  still need help? or ticket closed because help doesn't need anymore?
