### ISSUE TITLE
v1.0.45 Crashes during sync when upgrading from v1.0.41

### ISSUE THREAD

**Issue by JedHat** [hyle-team/zano#107]
https://drive.google.com/file/d/1Vl3LqPi2Fq8QZdZ623fl9f1hN9PYypzh/view?usp=sharing

log file 

after restarting wallet it synced fine after the crash

**Comment by Andreevsky** [comment]
There was similar issue that user @Tbear had. 
Build v1.0.45[9ade3f7] crashed during synchronizing from updating from v41. But later he deleted previeues appdata and then application crashed again during sync.
Here is log:
https://drive.google.com/uc?id=1p1ZjniJ5k4l-EY7LNBnghvIzl5njDPDk&export=download

**Comment by cryptozoidberg** [comment]
@JedHat  Can I ask you to check if there is crash dump file(s) in the data folder(same folder as logs)?

**Comment by sowle** [comment]
@JedHat Namely, we need crashdump_DESKTOP-JVTLT3P_2019-08-22_01-05-46.dmp that as I far as I can seen should be in your C:\Users\USERNAME\AppData\Roaming\Zano

**Comment by JedHat** [comment]
ok so that crash dump file is 3.6 Gb , you still want me to upload it ?

**Comment by cryptozoidberg** [comment]
@JedHat  absolutely! It would be much appreciated. I can share you ftp access to upload on our server. Send me DM in discord or to email if you want to use it.

**Comment by JedHat** [comment]
will do thanks
