### ISSUE TITLE
Password required after lockup timer expire at no-master password mode

### ISSUE THREAD

**Issue by Andreevsky** [hyle-team/zano#111]
If user choose don't use master password and then lockup timer expire then application will logout and ask for master password. Any password accepts well in that case for the first time, but for second time lockup only empty password accepts. 
It may be confusing to what to enter as password for user. 
**Password for opened wallets doesn't required again after lockup in no-master pass mode**

> v1.0.54[dbbef6a]

**Comment by sowle** [comment]
Seems to be fixed by dbb3bb7
