### ISSUE TITLE
Error dispays on windows 7

### ISSUE THREAD

**Issue by Andreevsky** [hyle-team/zano#118]
IlhamArsk reported bug:

![photo](https://user-images.githubusercontent.com/16042035/64693977-37a69d00-d4a1-11e9-9aba-dc1d8b2b1c69.jpg)

That error displays few times per day. Zano work 24/7.
On Windows 7. Didn't happend before update.

> v1.1.0.57[b77b915]

[Zano.log](https://github.com/hyle-team/zano/files/3600538/Zano.log)

**Comment by sowle** [comment]
The log has no error, BUT the user ran THREE copies of Zano simultaneously.

In order to identify the disk when it happens again:
Find this error event in Window's Event Viewer, click the Details tab to see the details.

**Comment by cryptozoidberg** [comment]
@Andreevsky

**Comment by Andreevsky** [comment]
IlhamArsk temporary solve this issue by insert memory card in cardreader. As he said, after "disk1" was in system error no longer displayed.
Im can't reproduce that bug by inserting and removing usb flash/hdd

**Comment by sowle** [comment]
Many attempts to reproduce this bug in Windows 7 have no success.
Reopen if smbd managed to reproduce somehow
