### ISSUE TITLE
crash after updating from v41 version

### ISSUE THREAD

**Issue by Andreevsky** [hyle-team/zano#119]
alex_grechko had issue about zano crash after updating from v41 to v57 version.
OS was windows 2008 server.
Crashdump was not created.

[last_part_log.txt](https://github.com/hyle-team/zano/files/3636866/last_part_log.txt)

**Comment by cryptozoidberg** [comment]
Thanks for report.
Little clarification - it's not a crash, it's a fault on lmdb initialization with national symbols in data folder path.
@sowle can you take care of this?

**Comment by Andreevsky** [comment]
fixed
