### ISSUE TITLE
Set up Coverity (static code analysis)

### ISSUE THREAD

**Issue by sowle** [hyle-team/zano#120]
Set up Coverity and incorporate it in CI scheme.

**A note Regarding double try-catch.**
They seem to be useless in our case because we're using C++11
In C++11 another exception cannot be thrown if there's already one in-flight, it will trigger `std::terminate` immediately. What's to do:
1. Implement custom `std::terminate` handler to catch and log such issues (at least we will be aware that smth went wrong) -- **done**
2.  Consider adding to the code standard using `noexcept(false)` in destructors.
3. Make all logging routines and mactors excepton-safe.
4. Make sure all this stuff passes Covetity 
5. Refactor CATCH_* macros

**Comment by cryptozoidberg** [comment]
Coverity Scan integration is setup: https://scan.coverity.com/projects/zanoproject 
TODO: add automation

**Comment by cryptozoidberg** [comment]
First iteration of fixes finished, new iteration planed with #149
