### ISSUE TITLE
Small GUI bugs

### ISSUE THREAD

**Issue by Andreevsky** [hyle-team/zano#126]
> v1.1.0.65[455ac69]
> ubuntu 18.04

Letter "g" displays cutted at the bottom:
https://monosnap.com/file/7lzXP1VpjW6SPjri4rDCbiHA6a05o3

**Comment by Andreevsky** [comment]
scale settings block isn't translated at any other languages (any of them)
https://take.ms/gvnTX

**Comment by Andreevsky** [comment]
close wallet button message isn't translated at any other languages:
https://take.ms/faD1N

**Comment by Andreevsky** [comment]
info message about alias edit displays at wrong place:
https://take.ms/uIJca

(happend when cursor was over Alias field)

**Comment by Andreevsky** [comment]
help icon "?" displays wrong "cutted":
https://take.ms/OYw2Z

(at scale 125%)

**Comment by Andreevsky** [comment]
month and day isn't translated at any other languages:
https://take.ms/2pB6s

**Comment by cryptozoidberg** [comment]
Need to fix only this issue: 

> scale settings block isn't translated at any other languages (any of them)
> https://take.ms/gvnTX
