### ISSUE TITLE
Fix problem with nodes which is not updated to hardfork1

### ISSUE THREAD

**Issue by cryptozoidberg** [hyle-team/zano#128]
`SYNCHRONIZATION started
2019-Oct-08 17:01:25.945078 [P2P0][158.174.112.188:52453 INC]Inital sync data returned unknown top block (<d7efbc0dc14e16f6efeb1d416e72d90c8efc0724de21d8bd960e04e8a1aa5c31>): 218535 -> 195159 [23376 blocks (-16 days) ahead]
SYNCHRONIZATION started
2019-Oct-08 17:01:28.623384 [P2P1][60.49.41.157:53558 INC]Inital sync data returned unknown top block (<d7efbc0dc14e16f6efeb1d416e72d90c8efc0724de21d8bd960e04e8a1aa5c31>): 218535 -> 195159 [23376 blocks (-16 days) ahead]
SYNCHRONIZATION started
2019-Oct-08 17:01:35.480046 [P2P7][67.182.192.98:60504 INC]Inital sync data returned unknown top block (<a7e82356263c98d17fe41317bce73d0f9fa5ad062846ed3552dd3399ae846a38>): 218535 -> 194936 [23599 blocks (-16 days) ahead]
SYNCHRONIZATION started
2019-Oct-08 17:01:41.756593 [P2P2][96.236.39.26:52666 INC]Inital sync data returned unknown top block (<a7e82356263c98d17fe41317bce73d0f9fa5ad062846ed3552dd3399ae846a38>): 218535 -> 194936 [23599 blocks (-16 days) ahead]`

**Comment by sowle** [comment]
![image](https://user-images.githubusercontent.com/29127158/66754251-3dc3db00-ee9e-11e9-892d-35d16b78730b.png)
