### ISSUE TITLE
Market Price Display

### ISSUE THREAD

**Issue by minerkid** [hyle-team/zano#129]
this is a feature i think would be very nice to have if possible 

would it be possible to make the Zano price update live vs just updating on initial startup 
im not sure if this could be done without being a security issue , maybe at least could have a "Refresh" button 

Cheers

**Comment by cryptozoidberg** [comment]
Will be done in next release

**Comment by cryptozoidberg** [comment]
@zetov need to implement idle price update (once in 30 seconds)

**Comment by cryptozoidberg** [comment]
Fixed
