### ISSUE TITLE
Wallet just stops trying to connect after rapidly trying to connect to daemon

### ISSUE THREAD

**Issue by cryptozoidberg** [hyle-team/zano#130]
Yeah, similarly wallet just stops trying to connect after rapidly trying to connect to daemon a certain number of times. So I can just start and immediately start the daemon and they never try to connect to the daemon again.

_Originally posted by @clintar in https://github.com/hyle-team/zano/issues/110#issuecomment-540352367_

**Comment by clintar** [comment]
Oops, meant to say stop and immediately start. 
Here is the end of the output. Looks like it just retries repeatedly with no pausing and gives up withing a few seconds based on looking at the logs:
`2019-Oct-09 14:38:19.353561 [RPC0][ERROR] Location: 
[bool epee::net_utils::http::invoke_request(const string&, t_transport&, unsigned int, const epee::net_utils::http::http_response_info**, const string&, const string&, const fields_list&) [with t_transport = epee::net_utils::http::http_simple_client; std::__cxx11::string = std::__cxx11::basic_string<char>; epee::net_utils::http::fields_list = std::__cxx11::list<std::pair<std::__cxx11::basic_string<char>, std::__cxx11::b
asic_string<char> > >]] @ /home/clintar/zano-build/contrib/epee/include/net/http_client.h:874
STACK
/home/clintar/zano-build/build/release/src/simplewallet(+0x154d35) [0x5579cd939d35]
/home/clintar/zano-build/build/release/src/simplewallet(+0x15e382) [0x5579cd943382]
/home/clintar/zano-build/build/release/src/simplewallet(+0x17899d) [0x5579cd95d99d]
/home/clintar/zano-build/build/release/src/simplewallet(_ZN5tools23default_http_core_proxy28call_COMMAND_RPC_GET_TX_POOLERKN8currency23COMMAND_RPC_GET_TX_POOL7requestERNS2_8responseE+0x55b) [0x5579cdaa911b]
/home/clintar/zano-build/build/release/src/simplewallet(_ZN5tools7wallet212scan_tx_poolERb+0xfe) [0x5579cda766de]
/home/clintar/zano-build/build/release/src/simplewallet(+0x1d50e1) [0x5579cd9ba0e1]
/home/clintar/zano-build/build/release/src/simplewallet(_ZN4epee9net_utils18boosted_tcp_serverINS0_4http19http_custom_handlerINS0_23connection_context_baseEEEE20global_timer_handlerEN5boost10shared_ptrINS6_25idle_callback_conext_baseEEE+0x2b) [0x5579cd9cef2b]
/home/clintar/zano-build/build/release/src/simplewallet(_ZN5boost4asio6detail12wait_handlerINS_3_bi6bind_tIbNS_4_mfi3mf1IbN4epee9net_utils18boosted_tcp_serverINS8_4http19http_custom_handlerINS8_23connection_context_baseEEEEENS_10shared_ptrINSE_25idle_callback_conext_baseEEEEENS3_5list2INS3_5valueIPSE_EENSK_ISH_EEEEEEE11do_completeEPvPNS1_19scheduler_operationERKNS_6system10error_codeEm+0xde) [0x5579cd9c285e]
/home/clintar/zano-build/build/release/src/simplewallet(_ZN4epee9net_utils18boosted_tcp_serverINS0_4http19http_custom_handlerINS0_23connection_context_baseEEEE13worker_threadEv+0x932) [0x5579cd9ce5b2]
/usr/lib/x86_64-linux-gnu/libboost_thread.so.1.67.0(+0x14af5) [0x7fea04407af5]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x9182) [0x7fea0444c182]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7fea03e30b1f]
 Message:
failed to connect localhost:11211
2019-Oct-09 14:38:19.353824 [RPC0]Failed to invoke http request to  http://localhost:11211/get_tx_pool.bin
2019-Oct-09 14:38:19.353886 [RPC0][ERROR] Location: 
[bool epee::net_utils::http::invoke_request(const string&, t_transport&, unsigned int, const epee::net_utils::http::http_response_info**, const string&, const string&, const fields_list&) [with t_transport = epee::net_utils::http::http_simple_client; std::__cxx11::string = std::__cxx11::basic_string<char>; epee::net_utils::http::fields_list = std::__cxx11::list<std::pair<std::__cxx11::basic_string<char>, std::__cxx11::b
asic_string<char> > >]] @ /home/clintar/zano-build/contrib/epee/include/net/http_client.h:874
STACK
/home/clintar/zano-build/build/release/src/simplewallet(+0x154d35) [0x5579cd939d35]
/home/clintar/zano-build/build/release/src/simplewallet(+0x15e382) [0x5579cd943382]
/home/clintar/zano-build/build/release/src/simplewallet(+0x17899d) [0x5579cd95d99d]
/home/clintar/zano-build/build/release/src/simplewallet(_ZN5tools23default_http_core_proxy28call_COMMAND_RPC_GET_TX_POOLERKN8currency23COMMAND_RPC_GET_TX_POOL7requestERNS2_8responseE+0x55b) [0x5579cdaa911b]
/home/clintar/zano-build/build/release/src/simplewallet(_ZN5tools7wallet212scan_tx_poolERb+0xfe) [0x5579cda766de]
/home/clintar/zano-build/build/release/src/simplewallet(+0x1d50e1) [0x5579cd9ba0e1]
/home/clintar/zano-build/build/release/src/simplewallet(_ZN4epee9net_utils18boosted_tcp_serverINS0_4http19http_custom_handlerINS0_23connection_context_baseEEEE20global_timer_handlerEN5boost10shared_ptrINS6_25idle_callback_conext_baseEEE+0x2b) [0x5579cd9cef2b]
/home/clintar/zano-build/build/release/src/simplewallet(_ZN5boost4asio6detail12wait_handlerINS_3_bi6bind_tIbNS_4_mfi3mf1IbN4epee9net_utils18boosted_tcp_serverINS8_4http19http_custom_handlerINS8_23connection_context_baseEEEEENS_10shared_ptrINSE_25idle_callback_conext_baseEEEEENS3_5list2INS3_5valueIPSE_EENSK_ISH_EEEEEEE11do_completeEPvPNS1_19scheduler_operationERKNS_6system10error_codeEm+0xde) [0x5579cd9c285e]
/home/clintar/zano-build/build/release/src/simplewallet(_ZN4epee9net_utils18boosted_tcp_serverINS0_4http19http_custom_handlerINS0_23connection_context_baseEEEE13worker_threadEv+0x932) [0x5579cd9ce5b2]
/usr/lib/x86_64-linux-gnu/libboost_thread.so.1.67.0(+0x14af5) [0x7fea04407af5]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x9182) [0x7fea0444c182]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7fea03e30b1f]
 Message:
failed to connect localhost:11211
2019-Oct-09 14:38:19.354115 [RPC0]Failed to invoke http request to  http://localhost:11211/get_tx_pool.bin
2019-Oct-09 14:38:19.354177 [RPC0][ERROR] Location: 
[bool epee::net_utils::http::invoke_request(const string&, t_transport&, unsigned int, const epee::net_utils::http::http_response_info**, const string&, const string&, const fields_list&) [with t_transport = epee::net_utils::http::http_simple_client; std::__cxx11::string = std::__cxx11::basic_string<char>; epee::net_utils::http::fields_list = std::__cxx11::list<std::pair<std::__cxx11::basic_string<char>, std::__cxx11::b
asic_string<char> > >]] @ /home/clintar/zano-build/contrib/epee/include/net/http_client.h:874
STACK
/home/clintar/zano-build/build/release/src/simplewallet(+0x154d35) [0x5579cd939d35]
/home/clintar/zano-build/build/release/src/simplewallet(+0x15e382) [0x5579cd943382]
/home/clintar/zano-build/build/release/src/simplewallet(+0x17899d) [0x5579cd95d99d]
/home/clintar/zano-build/build/release/src/simplewallet(_ZN5tools23default_http_core_proxy28call_COMMAND_RPC_GET_TX_POOLERKN8currency23COMMAND_RPC_GET_TX_POOL7requestERNS2_8responseE+0x55b) [0x5579cdaa911b]
/home/clintar/zano-build/build/release/src/simplewallet(_ZN5tools7wallet212scan_tx_poolERb+0xfe) [0x5579cda766de]
/home/clintar/zano-build/build/release/src/simplewallet(+0x1d50e1) [0x5579cd9ba0e1]
/home/clintar/zano-build/build/release/src/simplewallet(_ZN4epee9net_utils18boosted_tcp_serverINS0_4http19http_custom_handlerINS0_23connection_context_baseEEEE20global_timer_handlerEN5boost10shared_ptrINS6_25idle_callback_conext_baseEEE+0x2b) [0x5579cd9cef2b]
/home/clintar/zano-build/build/release/src/simplewallet(_ZN5boost4asio6detail12wait_handlerINS_3_bi6bind_tIbNS_4_mfi3mf1IbN4epee9net_utils18boosted_tcp_serverINS8_4http19http_custom_handlerINS8_23connection_context_baseEEEEENS_10shared_ptrINSE_25idle_callback_conext_baseEEEEENS3_5list2INS3_5valueIPSE_EENSK_ISH_EEEEEEE11do_completeEPvPNS1_19scheduler_operationERKNS_6system10error_codeEm+0xde) [0x5579cd9c285e]
/home/clintar/zano-build/build/release/src/simplewallet(_ZN4epee9net_utils18boosted_tcp_serverINS0_4http19http_custom_handlerINS0_23connection_context_baseEEEE13worker_threadEv+0x932) [0x5579cd9ce5b2]
/usr/lib/x86_64-linux-gnu/libboost_thread.so.1.67.0(+0x14af5) [0x7fea04407af5]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x9182) [0x7fea0444c182]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7fea03e30b1f]
 Message:
failed to connect localhost:11211
2019-Oct-09 14:38:19.354427 [RPC0]Failed to invoke http request to  http://localhost:11211/get_tx_pool.bin
2019-Oct-09 14:38:19.354433 [RPC0][ERROR] Location: 
[void tools::wallet2::scan_tx_pool(bool&)] @ /home/clintar/zano-build/src/wallet/wallet2.cpp:1295
STACK
/home/clintar/zano-build/build/release/src/simplewallet(+0x154d35) [0x5579cd939d35]
/home/clintar/zano-build/build/release/src/simplewallet(_ZN5tools7wallet212scan_tx_poolERb+0x2c3a) [0x5579cda7921a]
/home/clintar/zano-build/build/release/src/simplewallet(+0x1d50e1) [0x5579cd9ba0e1]
/home/clintar/zano-build/build/release/src/simplewallet(_ZN4epee9net_utils18boosted_tcp_serverINS0_4http19http_custom_handlerINS0_23connection_context_baseEEEE20global_timer_handlerEN5boost10shared_ptrINS6_25idle_callback_conext_baseEEE+0x2b) [0x5579cd9cef2b]
/home/clintar/zano-build/build/release/src/simplewallet(_ZN5boost4asio6detail12wait_handlerINS_3_bi6bind_tIbNS_4_mfi3mf1IbN4epee9net_utils18boosted_tcp_serverINS8_4http19http_custom_handlerINS8_23connection_context_baseEEEEENS_10shared_ptrINSE_25idle_callback_conext_baseEEEEENS3_5list2INS3_5valueIPSE_EENSK_ISH_EEEEEEE11do_completeEPvPNS1_19scheduler_operationERKNS_6system10error_codeEm+0xde) [0x5579cd9c285e]
/home/clintar/zano-build/build/release/src/simplewallet(_ZN4epee9net_utils18boosted_tcp_serverINS0_4http19http_custom_handlerINS0_23connection_context_baseEEEE13worker_threadEv+0x932) [0x5579cd9ce5b2]
/usr/lib/x86_64-linux-gnu/libboost_thread.so.1.67.0(+0x14af5) [0x7fea04407af5]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x9182) [0x7fea0444c182]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7fea03e30b1f]
 Message:
!r. THROW EXCEPTION: error::no_connection_to_daemon
2019-Oct-09 14:38:19.354594 [RPC0]/home/clintar/zano-build/src/wallet/wallet2.cpp:1295:N5tools5error23no_connection_to_daemonE: no connection to daemon, request = get_tx_poo`

It never continues after that even though daemon has started.

**Comment by cryptozoidberg** [comment]
@clintar thanks for details, we'll take care of it.

**Comment by sowle** [comment]
Seems to be fixed. @Andreevsky please, check.
