### ISSUE TITLE
Search in History tab (Gui)

### ISSUE THREAD

**Issue by minerkid** [hyle-team/zano#139]
would it be possible to add a "Search" or "Sort" function in the history tab to sort between regular transactions and POS rewards.

its a bit of  a pain to scroll thru many POS transactions to find a transaction sent to another wallet etc 

not sure this is a viable option but it would be really handy

**Comment by cryptozoidberg** [comment]
it's definitely possible, for the beginning we can implement a search option, what should be used to search? tx id, payment id, address, anything else?

**Comment by minerkid** [comment]
i was thinking something like a small drop down that you could select "Hide POS tx" or something like that just because they get so many

**Comment by cryptozoidberg** [comment]
@minerkid  it feels like you making too much from staking... 
@zetov  what do you think? can we make it?

**Comment by cryptozoidberg** [comment]
Here is how it should look like: 
![image](https://user-images.githubusercontent.com/7261328/90651184-0439ca00-e23d-11ea-819a-07a20c6580f3.png)
![image](https://user-images.githubusercontent.com/7261328/90651246-16b40380-e23d-11ea-9dc2-5b3f335c76c3.png)
Graphics in attachement to this ticket. 

[PSD_ZANO_WALLET_transaction_pagi+button.zip](https://github.com/hyle-team/zano/files/5097298/PSD_ZANO_WALLET_transaction_pagi%2Bbutton.zip)
