### ISSUE TITLE
Error in gui after if lost internet connection

### ISSUE THREAD

**Issue by Andreevsky** [hyle-team/zano#148]
Zano app was running for few days (v75 build on win10). After that after restore from tray there was several errors displayed at gui. Log level was set to 1. Database was MDBX. Few times machine was in sleep mode and restored. Log is here: ftp://upload36@144.76.183.143/Zano-error_v75.zip

I had reproduced that bug again by disabling wi-fi connection. After minute get errors displayed at gui. After clicking OK app was working fine. Another log:
[Zano.log](https://github.com/hyle-team/zano/files/4003706/Zano.log)

![Snapshot+2019-12-25+15 36 31](https://user-images.githubusercontent.com/16042035/71494403-18692b00-2858-11ea-952b-04e2051fbeaf.jpg)

> v1.1.4.75[8548e2d]
> win 10

**Comment by sowle** [comment]
Could not reproduce neither in build 75 nor in 77 (latest).
