### ISSUE TITLE
Set up first checkpoint

### ISSUE THREAD

**Issue by cryptozoidberg** [hyle-team/zano#150]
Set up first checkpoint, validate correctness of prunning mechanism, set up pre-downloaded binaries

**Comment by sowle** [comment]
I do all the stuff on the testnet to make sure everything is okay.

**Comment by sowle** [comment]
set up in 9efc77f95b5c373e50bc4ac4eea1dcb4ec2e8b6f and 6356b9b09d548914655a064dd2ad64becb3adb5c
