### ISSUE TITLE
Make alias registration error messages more informative

### ISSUE THREAD

**Issue by OrsonJ** [hyle-team/zano#154]
"Alias has wrong name" isn't very informative. It would be better if the message explained why, e.g. "All characters must be lowercase".

![image](https://user-images.githubusercontent.com/59993846/72593414-341a9b00-3905-11ea-98b7-f8c3f1c6581a.png)

Also, if the '@' at the start of the alias is obligatory, maybe it should be prefilled and uneditable since any other character is invalid anyway.

**Comment by cryptozoidberg** [comment]
Thanks for reporting, totally agree with that, will implement it in one of the nearest builds.

**Comment by sowle** [comment]
@cryptozoidberg This is an entirely GUI-specific task. Aliases are being checked on the front-end

**Comment by cryptozoidberg** [comment]
Change error message to:  "Invalid name: allowed symbols "0-9", "a-z", "-", ".""
