### ISSUE TITLE
Another bug in the history tab (GUI)

### ISSUE THREAD

**Issue by minerkid** [hyle-team/zano#156]
this issue happens when user is viewing previous pages of TX history and wallet receives a new transaction, the incoming transaction will show at the top of the page no matter what page number the user is on.

here is screen shot of the issue 
![image](https://user-images.githubusercontent.com/37032313/74093972-5ab09980-4a9f-11ea-96b6-3a074d2168c7.png)

here i am viewing a page of very old transactions, i sent some coins to myself from another wallet and tx shows on same page when it should not show at all

**Comment by sowle** [comment]
Confirmed in build 1.1.5.80[135eed3]

**Comment by sowle** [comment]
seems fixed in ca7899b234df36316011da5e3077498f2af59795
