### ISSUE TITLE
Small issue in GUI Graphics 

### ISSUE THREAD

**Issue by minerkid** [hyle-team/zano#157]
with new build this issue happens when you have many wallets open ... the new placement of the "X" to close individual wallets is ok but they do not scroll with the panel of wallets on the left side. And they also show it strange place on the bottom.       see picture
![1 1 5 78issue](https://user-images.githubusercontent.com/37032313/75998165-0645e180-5ec6-11ea-9c27-9db095e0743b.jpg)

**Comment by sowle** [comment]
@zetov please, take a look on this

**Comment by sowle** [comment]
Fixed by c6c3d2264dac037e3e7da5023431a79c97f3520a
