### ISSUE TITLE
GUI: tx history pagination is not working sometimes

### ISSUE THREAD

**Issue by sowle** [hyle-team/zano#163]
A mining wallet with approx 50k of UTXO associated (87k outputs total) was opened by Zano gui app and started synchronizing from the scratch (e.g. restoring from the seed). The process took approx. half an hour because of the huge amount of incoming txs.

BUG: pagination on History tab is not working, all txs are displayed on page 1.  Build is irresponsive, tab switching takes several minutes.
![image](https://user-images.githubusercontent.com/29127158/78163853-99d0ea80-7451-11ea-9d70-e027b5aed488.png)

Notifications are shown with a different icon (X instead of i):
![image](https://user-images.githubusercontent.com/29127158/78164462-735f7f00-7452-11ea-95be-c96bf9cdb18f.png)

This is how normal notification looks:
![image](https://user-images.githubusercontent.com/29127158/78165326-d7cf0e00-7453-11ea-8241-ff1657e1746e.png)

**If the same wallet is already synced, all went okay and pagination is working properly.**

build v1.1.5.81[82db9da] @ windows 7x64

**Comment by cryptozoidberg** [comment]
Let's put toggle button to right bottom corner of the window: 
![image](https://user-images.githubusercontent.com/7261328/90570712-98aa1b00-e1b0-11ea-90b9-efc1ac9736f7.png)
