### ISSUE TITLE
Improve Wallet RPC API

### ISSUE THREAD

**Issue by cryptozoidberg** [hyle-team/zano#164]
Wallet RPC API should be improved to be compatible with most common API(walletd, monero).
Useful links:
https://web.getmonero.org/resources/developer-guides/wallet-rpc.html
https://web.archive.org/web/20170919152345/https://wiki.bytecoin.org/wiki/Bytecoin_RPC_Wallet_JSON_RPC_API
https://github.com/bcndev/bytecoin/blob/master/docs/Bytecoin-Wallet-Daemon-JSON-RPC-API.md

**Comment by Aimeelu668** [comment]
楼主大大总结的很到位！不过自己开发的钱包都是热钱包机制，节点同步慢，归集非常麻烦，最重要的是这些私钥存在服务器上很危险，天天被黑客盯着。当时我们平台有50多万会员，为了解决钱包问题折腾了一年，最终放弃了，选择了优盾钱包（ https://www.uduncloud.com）。
通过API直接接入就行，有独立客户端操作审核、归集等，私钥也是自己在客户端上管理，服务器上不存。用了快一年，没有出现安全问题，财务都反馈说体验很好。我们也终于可以专注于业务开发了。推荐试试

**Comment by cryptozoidberg** [comment]
Moved to backlog
