### ISSUE TITLE
Implement API for searching transactions by parameters

### ISSUE THREAD

**Issue by cryptozoidberg** [hyle-team/zano#165]
`search_for_transactions`

Paramters:
tx_hash - hash of transaction, if specified then used as tx id
in — boolean; if true then incoming transactions will be taken into account.
out — boolean; if true then outgoing transactions will be taken into account.
pending — boolean; not supported yet, will be ignored.
failed — boolean; not supported yet, will be ignored.
pool — boolean; if true then unconfirmed in/out txs will be taken into account.
filter_by_height — boolean; if true then transfers will be filtered by block height.
min_height — integer; minimum block height (including).
max_height — integer; maximum block height (including).

**Comment by sowle** [comment]
af8ef3399add3f3380180d6fb512c403e06268dc
cacd5206ef709d3501d4dbd6d9ec64618dc4b1b9
c12f8487fb3f1c3a4494e3b0d68c12d1f0504929
