### ISSUE TITLE
Implement Zano url scheme

### ISSUE THREAD

**Issue by cryptozoidberg** [hyle-team/zano#173]
Implement Zano url scheme for MacOS/Windows/Linux. (proposed by Gigabyted)

**Comment by Gigabyted** [comment]
An implementation such as the BIP21 (https://en.bitcoin.it/wiki/BIP_0021) would allow a much more better interactions between external application (such as a web browser) with the GUI Wallet.  

This way it would be possible to interact with different features within the wallet, such as sending coins, adding contacts and  interacting with marketplace.

A simple example would be to see some items listed from the marketplace on a website and a Buy button that would prefilf the wall send screen (security of course has to be respected).

**Comment by Gigabyted** [comment]
Monero also supports it this way: https://monero.fandom.com/wiki/URI_formatting

In our case it could probably pushed further like interacting with marketplace features...

**Comment by cryptozoidberg** [comment]
Moved to BackLog
