### ISSUE TITLE
Implement auditable and auditable watch-only wallets highlightning in GUI

### ISSUE THREAD

**Issue by sowle** [hyle-team/zano#175]
Booleans `is_auditable` and `is_watch_only` are now available in `wallet_info` (besides `address` and `pass`).

There are three possible cases:
  1. Normal wallet, `is_watch_only == false` and `is_auditable == false`.
  2. Auditable wallet, `is_watch_only == false` and `is_auditable == true`.
  1. Auditable watch-only wallet, `is_watch_only == true` and `is_auditable == true`.

They should be highlighted differently in the interface.

Non-auditable watch-only wallets are for cold-signing only and not accessible in GUI.

The following limitations should be applied to auditable watch-only wallets (but **not** for auditable):
  1. Staking switch should be hidden.
  1. Send and Contracts tabs should be inaccesible.

**Comment by cryptozoidberg** [comment]
Here is an example of how different wallets might look like. Green - "auditable", purple - "tracking",
![screen-main_dark_10](https://user-images.githubusercontent.com/7261328/83780044-f4263b80-a68c-11ea-9211-925045f7b731.png)
Those color marks(or we can call it tabs) are sliding down on hover mouse, and show text:
![opened](https://user-images.githubusercontent.com/7261328/83780033-f12b4b00-a68c-11ea-9190-094cc9165565.png)
Text supposed to be clickable, and click open browser with the link to documentation, which explain what does "tracking" "or auditable" means.

**Comment by cryptozoidberg** [comment]
https://www.dropbox.com/s/b2dd1gcw5cjj03w/PSD_ZANO_WALLET-auditable-tracking.zip?dl=0

**Comment by Andreevsky** [comment]
Works fine at v1.1.7.94[32f5881], but:
1. Link on clicking go to zano.org (not to documentation).
2. Tracking-auditable wallets tabs there named "Watch-only" and not "Tracking" as described.

![Zano 2020-07-18 21 43 38](https://user-images.githubusercontent.com/16042035/87859707-de6c8d00-c93f-11ea-8bed-2f6f75f97e4d.png)
