### ISSUE TITLE
Implement default mixin value and no mixin for auditable

### ISSUE THREAD

**Issue by sowle** [hyle-team/zano#176]
1. Now default mixin hardcoded by me to 10 in compiled JS scripts (see commits 05f15d5, dbf7049, 932f66b). We need to re-implement it in a straight way, by defining a constant in source JS code.

  1. For auditable wallets (`is_auditable == true`) mixin on tx sending should always be zero. The mixin edit box should be inaccessible for change.

**Comment by sowle** [comment]
Seems to be fixed, should be tested prior to release

**Comment by Andreevsky** [comment]
fixed at 1.1.7.91[25f8dfb]
