### ISSUE TITLE
Move to regular precompiled headers from cmake 

### ISSUE THREAD

**Issue by cryptozoidberg** [hyle-team/zano#178]

**Comment by sowle** [comment]
<img width="676" alt="image" src="https://user-images.githubusercontent.com/29127158/89408858-c19acc80-d729-11ea-871b-5118b7b5f218.png">
Tests show that new CMake-powered PCHs are comparable in win-release configuration but **slowing down** building in win-debug. Also they speed up on gcc a little.
I end up with a combined scheme: using old PCHs for windows and new for Linux.
