### ISSUE TITLE
GUI: Enlarge  QRCode on desktop version

### ISSUE THREAD

**Issue by cryptozoidberg** [hyle-team/zano#180]
Currently qrcode square is quite small, it causes difficulties to scan it on some devices.

![image](https://user-images.githubusercontent.com/7261328/84285773-2842a600-ab3e-11ea-95ea-324bcba59baa.png)

**Comment by sowle** [comment]
Looks fixed, the scale can be adjusted with `RCV_ADDR_QR_SCALE` in JS consts

**Comment by Andreevsky** [comment]
Fixed, but doesn't scale with settings ( 75-150%).
