### ISSUE TITLE
History tab: page is not selected by default, sent tx doesn't show up in the list

### ISSUE THREAD

**Issue by sowle** [hyle-team/zano#184]
1. Open a wallet, don't click on the page numbers.
2. Send a tx.
3. Go to History tab.
The last page is not selected, tx doesn't show up:
![image](https://user-images.githubusercontent.com/29127158/85144970-91b86800-b254-11ea-8da3-288639c609d4.png)
4. If click on last page number ("1"), tx shows up:
<img width="820" alt="image" src="https://user-images.githubusercontent.com/29127158/85144811-603f9c80-b254-11ea-8551-49772e3ca9d7.png">

**Comment by sowle** [comment]
Looks like fixed. Needs to be checked.

**Comment by Andreevsky** [comment]
Works fine at v1.1.7.94[32f5881]
