### ISSUE TITLE
Consider raising the alias fee to 5 Zano

### ISSUE THREAD

**Issue by blackholebrowsing** [hyle-team/zano#187]
Consider also raising the alias fee in general. Just as the tx fee had to be raised I think it may be time to raise the alias fee. This was discussed earlier today in the discord.

0.12 is too low.

Something that crossed my mind a few months back was how I could scrape the usernames of the most popular crypto influencers and say make a top 10,000 list, and then get a script for registering all their alias's ahead of time. Since the fee is only 0.12 to register, that is only 1200 Zano, to register 10,000 whale/influencer usernames. 

Its too low, that's only a few hundred dollars, and it would ruin the experience for everyone. I am nice enough to not do that, but someone who's a bit opportunistic may try it. Or even just as a way to slow adoption.

I think somewhere between 3 to 5 Zano may be better.  

Miners will also be happier about it, the possibility of 4 or 6 Zano blocks (if the coins are distributed as a fee and not burned, the explorer appears to show they aren't passed on to the miners)

By increasing it, you drastically reduce the risk of squatting tens of thousands of crypto twitter handle names and spam registrations.

**Comment by blackholebrowsing** [comment]
I would also add that I believe alias's will become worth quite a bit if I had to guess, as these will be interconnected with the entire ecosystem, from store names, to messaging, to just being able to 

Lets not give them away at 0.12 Zano, that's not sustainable nor is it wise to devalue alias's in that way. I suspect at some point there will be a thriving secondary market for them in the marketplace, which will be interesting to watch. I'm thinking out 7 years from now, I could totally see the value in picking some of the more unique names now. But don't leave it at 0.12, please.

**Comment by cryptozoidberg** [comment]
Make sense for me. Technically aliases price is a 10x of median fee in transactions pf the last week. So, to make it more expensive we'll have to make a hard fork. I believe we'll do that update with the next hard fork, which is expected in the next months with Atomic Swaps implementation.

**Comment by cryptozoidberg** [comment]
Moved to backlog
