### ISSUE TITLE
Wallet name auto fill bug

### ISSUE THREAD

**Issue by Andreevsky** [hyle-team/zano#194]
Wallet name doesn't autofill at the application form after opening wallet from file. At the build 1.1.7.91 after opening wallet "wallet name" field is empty. At previous builds (1.1.6.87)  wallet name was auto filled with same name as wallet file.

Video of bug:
https://monosnap.com/file/TY1xvHM1auEqZ4M4ZhuJeuNdjk0kKr

Win10
Build 1.1.7.91

**Comment by cryptozoidberg** [comment]
Fixed in 1.1.7.95
