### ISSUE TITLE
Add confirmation when Copy address button is hit on mobile wallet

### ISSUE THREAD

**Issue by Scryptee** [hyle-team/zano#195]
A confimation dialog box needs to briefly show when the copy address logo is hit, the blue shadow is too sublte and it feels weird when you don't see it.

"Address copied to clip board."

**Comment by cryptozoidberg** [comment]
@Scryptee Just to make sure - are we talking about mobile app here or desktop?

**Comment by Scryptee** [comment]
Mobile app

**Comment by cryptozoidberg** [comment]
@Scryptee  got it, thanks!
