### ISSUE TITLE
Change flat fee system to pay per bytes

### ISSUE THREAD

**Issue by Gigabyted** [hyle-team/zano#198]
The current fee system is a flat fee per transaction no matter how small or large that transaction is.

A healthy network should charge its fee based on the amount of resource its using, while an minimum fee could be set its important than more intensive use of the network, such as high mixing transactions or even spam, pay their share of the network based on how much resources they use.

**Comment by cryptozoidberg** [comment]
Moved to https://github.com/hyle-team/backlog/issues/2
