### ISSUE TITLE
Error message shows to much info 

### ISSUE THREAD

**Issue by minerkid** [hyle-team/zano#199]
v1.1.7.93 testing

Below is a screenshot of error message when trying to send a tx and there not being enough unlocked coins or coins in general
![image](https://user-images.githubusercontent.com/37032313/86977195-b8760a00-c141-11ea-847a-fb27486b58f3.png)

**Comment by Andreevsky** [comment]
Same bug v.94
https://take.ms/0Uy6Y

Log:
[Zano.log](https://github.com/hyle-team/zano/files/4904820/Zano.log)

**Comment by sowle** [comment]
The same thing happened when the requested anonymity set cannot be fulfilled (not such outputs for mixing in).
And the same happened in wallet RPC.
All fixed.
