### ISSUE TITLE
During opening wallet file, it name doesn't auto fill at field.

### ISSUE THREAD

**Issue by Andreevsky** [hyle-team/zano#204]
Video of reproduce:
https://monosnap.com/file/TY1xvHM1auEqZ4M4ZhuJeuNdjk0kKr

It happens with wallet files that was last syncronised and saved at 1.1.6.87 build.
Expected that wallet name auto fill at field "name" after choosing and opening file.

Win 10 2004
1.1.7.91[25f8dfb]

**Comment by sowle** [comment]
Duplicate for #194 (the same video attached also)
