### ISSUE TITLE
Add transaction list filters

### ISSUE THREAD

**Issue by Gigabyted** [hyle-team/zano#245]
Many wallets allow you to do a few things with their wallet transactions lists, like setting filters (transaction types, amounts, dates,...) and also allows column ordering (ascending/descending).  

At the same time a small button at the bottom of the list to export that list to a csv file could be also great, many wallets allow you to exports your (filtered) transactions to a file so you can open it into your favorite programs.

I could for example export all my sales to a file to then import it into my accounting system.

**Comment by cryptozoidberg** [comment]
Fixed
