### ISSUE TITLE
Add the account name to the notifcation window when an incoming tx arrives (especially stakes)

### ISSUE THREAD

**Issue by Gigabyted** [hyle-team/zano#246]
Would be quite useful to know which account got the stake in that notification window:

![image](https://user-images.githubusercontent.com/21089109/97732362-d084e700-1aac-11eb-8251-d9507b3f3ea0.png)

Even more important when you are watching someone else wallet (like dev funds).

Could also be quite useful to disable notification per wallet, since i dont really want to receive those but i want mine...

**Comment by crypjunkie** [comment]
Notifications can be turned off via Windows for wallet, though I assume that would include all contained wallets from within the app.
Would be a nice feature at some point to segregate notifications between various wallets contained within app too & as you requested from within wallet/GUI
