### ISSUE TITLE
Allow PoS mining reward address to be a alias

### ISSUE THREAD

**Issue by Gigabyted** [hyle-team/zano#263]
The simplewallet doesn't allow us to set zano alias as an address, this should be supported (and i haven't tested an integrated address) but every address types should be supported.

![image](https://user-images.githubusercontent.com/21089109/101363414-614e9f80-386f-11eb-92b7-6e1eba3c2032.png)

This is also true for the other issues i've posted over adding the PoS mining reward address into the GUI wallet.

Thanks for checking into this!

**Comment by matthewjamesr** [comment]
@cryptozoidberg You can assign this one to me :).
