### ISSUE TITLE
App Zano Crash

### ISSUE THREAD

**Issue by ArielM96** [hyle-team/zano#280]
The App zano Download landing page is crashed

**Comment by cryptozoidberg** [comment]
@ArielM96 Hi, thanks for the report,  Is it mobile application or desktop? What is called "download landing" page ?

**Comment by ArielM96** [comment]
Hi, It's Desktop, I mean the page where is the file to download

**Comment by cryptozoidberg** [comment]
can you send me logs to my email at andre on our domain?
