### ISSUE TITLE
I do not receive Zano

### ISSUE THREAD

**Issue by kylin21hd** [hyle-team/zano#282]
It's been 24 hours I have not received zano, check no txid report
txid: 533473fabbd76ff41ff8a1b324dd51ea70a422846efac70d31fe8f5afc0fba79
![zano ero](https://user-images.githubusercontent.com/82008941/113650373-4fb0c380-96ba-11eb-8177-986df17abc58.png)

**Comment by cryptozoidberg** [comment]
@kylin21hd  i don't see any tracks of this transaction. Can you provide more details over this issue: how did you send this tx(from exchange, from desktop app, from mobile app)?  Did you have your coins restored in your wallet after TX got vanished?

**Comment by cryptozoidberg** [comment]
closed due to lack of information. Re-open if need further assistance.
