### ISSUE TITLE
Comment to alias doesn't change after alias transfer

### ISSUE THREAD

**Issue by Andreevsky** [hyle-team/zano#284]
At the alias transfer screen there is also a comment field available for redactering. But if change that comment and then transfer alias, comment will not change.

https://monosnap.com/file/fWbhQRIi3nU20irQ1c1uanVn4qhTKp
https://monosnap.com/file/OITgcWcipm7L2RkJFD2T9ASz7bjxft

[Zano.log](https://github.com/hyle-team/zano/files/6346786/Zano.log)

os:windows 10
build: zano-win-x64-atomics-testnet-v1.1.8.115[6fea62d]

**Comment by cryptozoidberg** [comment]
Fixed
