### ISSUE TITLE
Wallet name doesn't change

### ISSUE THREAD

**Issue by Andreevsky** [hyle-team/zano#285]
Wallet name field is active for redactering, but doesn't updates after change name.

https://monosnap.com/file/dkZV59sLJpRAXRaFKL7wNz4rrAfLCV

[Zano_1.log](https://github.com/hyle-team/zano/files/6346957/Zano_1.log)

os:windows 10
build: zano-win-x64-atomics-testnet-v1.1.8.115[6fea62d]

**Comment by cryptozoidberg** [comment]
Fixed
