### ISSUE TITLE
Please add TESTNET Build options to Github Documentation

### ISSUE THREAD

**Issue by theneonirvana** [hyle-team/zano#287]
I could not find the basic information needed for making a TESTNET build. and had to bug the nice people in discord ;)

please add the 'cmake -D TESTNET=TRUE' commands as optional in the github documentation for future use. 

Thank you!

**Comment by sowle** [comment]
Thanks! Fixed in b09b6e39168a4b4c2bba82ec64f3d8cd8e0c4840
