### ISSUE TITLE
Zano Crashing when blockchain data is done downloading and is loading

### ISSUE THREAD

**Issue by doubleton1** [hyle-team/zano#288]
Whenever finish downloading blockchain data it crashes the wallet application and I have to start again, does anyone know how to fix this? 
You can contact me at .E#5769 on discord or @ahmed_brcl on instagram

**Comment by cryptozoidberg** [comment]
@doubleton1  i can't find user .E#5769 on discord and we don't use instagram for communicating.
Can you provide more details, and i would need a log file, please. (more details on log file location is here: https://docs.zano.org/docs/reporting-issues#log-files)
