### ISSUE TITLE
No confirmation text after changing settings and pressing save

### ISSUE THREAD

**Issue by YellowRoseCx** [hyle-team/zano#289]
I think it would be a good idea to make the Settings page in a wallet show "settings changed successfully" after clicking Save. Right now, pressing save gives no response to the user that their changes went through.
Something like this:
               
![Image](https://user-images.githubusercontent.com/80486540/119066929-87dc3f00-b9a6-11eb-996c-55e50c48df39.png)

        
Thank you!

**Comment by cryptozoidberg** [comment]
Fixed
