### ISSUE TITLE
Zano wallet sync but node returned unknown top block

### ISSUE THREAD

**Issue by b8engl** [hyle-team/zano#294]
The wallet is synced.

![wallet](https://user-images.githubusercontent.com/29173784/125159102-2e55ec80-e16d-11eb-9c2f-f3a140df491f.PNG)

But when I start the node the output says that I'm being from latest block. And gives a 38 days estimated sync.~

![node](https://user-images.githubusercontent.com/29173784/125159114-488fca80-e16d-11eb-891e-9929b951654c.PNG)

Is there a way to start from latest height (block)?

**Comment by cryptozoidberg** [comment]
Don't bother, it's just a nodes which is stuck in pre-hardfork state(because it wasn't updated), it actually says -38 days, so  you actually ahead of this these nodes on 38 days.
