### ISSUE TITLE
There's multiples typos on README.md

### ISSUE THREAD

**Issue by b8engl** [hyle-team/zano#295]
1. Prerequisites (typo at the end)
ii . Prerequisites for GUI version:
sudo apt-get install -y build-essential g++ python-dev autotools-dev libicu-dev libbz2-dev cmake git screen mesa-common-dev libglu1-mesa-dev`

2. Download and build Boost (link not working)
https://dl.bintray.com/boostorg/release/1.68.0/source/boost_1_68_0.tar.bz2

**Comment by b8engl** [comment]
Also with linux release v1.2.0.122 the compression file is wrong

**Comment by cryptozoidberg** [comment]
@sowle  can you take look

**Comment by b8engl** [comment]
@cryptozoidberg the new compressed linux file, gives libQt5Core.so.5 error.
[Previous](https://github.com/hyle-team/zano/issues/295#issuecomment-877807970) works well.

**Comment by sowle** [comment]
@b8engl 
>     1. Prerequisites (typo at the end)
Thanks, I'll fix the typo.

>     2. Download and build Boost (link not working)
>        https://dl.bintray.com/boostorg/release/1.68.0/source/boost_1_68_0.tar.bz2
It was fixed like 6 weeks ago in 907d428689c2d1f6647b3284bdbe58f0415e55d4  in develop. We'll merge it into the master at some point.

**Comment by sowle** [comment]
@b8engl 
> the new compressed linux file, gives libQt5Core.so.5 error.

Could you clarify, please? I honestly can't find any issue:
<img width="1126" alt="image" src="https://user-images.githubusercontent.com/29127158/126075616-fd97e45b-755a-45ac-b995-43a62d05abe2.png">
Zano.sh start okay as well.

**Comment by b8engl** [comment]
I see you do ll, using 20.04? I'm on 18.04...
I'm getting that error when I do `./Zano --stratum --stratum-miner-address=**** --log-level=2 --stratum-bind-port=11555`
Do I miss something?

**Comment by b8engl** [comment]
Resolved
