### ISSUE TITLE
Where's the info for the zano wallet stratum server?

### ISSUE THREAD

**Issue by b8engl** [hyle-team/zano#296]
what can we use when using stratum server, Is there any documentation available?
e.g --something

**Comment by cryptozoidberg** [comment]
@sowle can you provide guidance

**Comment by b8engl** [comment]
Do we have something like `--threads`?

**Comment by b8engl** [comment]
Found the inputs in source code

**Comment by cryptozoidberg** [comment]
Sorry for not being fast, it's a bit rush day. Don't hesitate to reach out me in discord in you need more help
