### ISSUE TITLE
Compilation for Windows

### ISSUE THREAD

**Issue by lassizness** [hyle-team/zano#299]
Can I compile a wallet for Windows from under Ubuntu?

**Comment by cryptozoidberg** [comment]
It is possible theoretically by using mingw for example, but we never done it with Zano by ourself.

**Comment by lassizness** [comment]
I am very grateful for your prompt reply. I'll experiment then =)

**Comment by cryptozoidberg** [comment]
If you will be able to do that, we would appreciate if you share instructions and pull request if needed!

**Comment by lassizness** [comment]
Yes of course. No problem =) I will close the ticket for now.
