### ISSUE TITLE
Transfers recieved not showing in gui.

### ISSUE THREAD

**Issue by clintar** [hyle-team/zano#3]
I sent my own address some .01 coin and I only have record of sending and none for receiving. I have only tried gui wallet for this. I did a second transfer to myself that was .01 ZNO and only the fee of the transfer showed in the gui. Sending wallet. There's no password.
[zano-wallet1.wallet.tar.gz](https://github.com/zano-project/zano/files/2795315/zano-wallet1.wallet.tar.gz)

**Comment by cryptozoidberg** [comment]
Please rebuild on current master and check it again. Thanks!

**Comment by clintar** [comment]
![screenshot_20190125_133617](https://user-images.githubusercontent.com/2761301/51771443-36f1ff80-20a6-11e9-914c-4a1b62af52ee.png)
did a resync and refresh in simplewallet on latest master and this is what I'm seeing still.

**Comment by clintar** [comment]
This is old and probably invalid

**Comment by cryptozoidberg** [comment]
Sorry, I didn't read this precisely the first time time. 
This is actually "as designed" behavior - wallet does an interpretation of the transactions based on the summary incoming and outgoing transfers inside one transaction. 
Let say, for example, that you have 10 coins output in the wallet, and you sending 9 coins to yourself, then transactions would looks like this:

10.0 - outgoing
8.99 - incoming (change)
9.0 incoming (actuall transfer to yourself)


After summarising everything you have just 0.01 coins were withdrawn from the wallet, which is a transaction fee.
