### ISSUE TITLE
Qt problems with Linux binary

### ISSUE THREAD

**Issue by output123** [hyle-team/zano#302]
First, Zano could not see any of its lib files, so I copied them from the Zano lib folder to my /usr/lib folder, and that worked.

Next, Zano could not find the Qt platform plugin "xcb" so I used the following command line and it found it:

./Zano -platformpluginpath /usr/lib/platforms

Next, Zano launched but with a ton of Qt related errors, could not find Qt WebEngine ICU, locales, and resources.

I am at my wits end, how do I solve all these problems, and are they common for everyone else trying to run Zano on Linux? Am I missing an installer somewhere?

**Comment by cryptozoidberg** [comment]
Hi! Sorry about you having this problem.
On linux with the binaries we distribute .sh file which properly launch it: https://github.com/hyle-team/zano/blob/master/utils/Zano.sh

Please try it and let me know if it worked for you.

**Comment by output123** [comment]
Thanks, the sh file you linked did not work for me, but I bashed the sh file in the latest 1.3.0.133 release and that opened the wallet. However, I am still getting the same errors:

Qt WebEngine ICU data not found at /home/user/Qt5.11.2/5.11.2/gcc_64/resources. Trying parent directory...
Qt WebEngine ICU data not found at /home/user/Qt5.11.2/5.11.2/gcc_64. Trying application directory...
Installed Qt WebEngine locales directory not found at location /home/user/Qt5.11.2/5.11.2/gcc_64/translations/qtwebengine_locales. Trying application directory...
Qt WebEngine locales directory not found at location /home/r/Documents/Zano/qtwebengine_locales. Trying fallback directory... Translations MAY NOT not be correct.
Qt WebEngine resources not found at /home/user/Qt5.11.2/5.11.2/gcc_64/resources. Trying parent directory...
Qt WebEngine resources not found at /home/user/Qt5.11.2/5.11.2/gcc_64. Trying application directory...
[0920/110137.649097:WARNING:resource_bundle_qt.cpp(115)] locale_file_path.empty() for locale 
Qt WebEngine ICU data not found at /home/user/Qt5.11.2/5.11.2/gcc_64/resources. Trying parent directory...
Qt WebEngine ICU data not found at /home/user/Qt5.11.2/5.11.2/gcc_64. Trying application directory...
Installed Qt WebEngine locales directory not found at location /home/user/Qt5.11.2/5.11.2/gcc_64/translations/qtwebengine_locales. Trying application directory...


and all of these:


qt.network.ssl: QSslSocket: cannot resolve CRYPTO_num_locks
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_set_id_callback
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_set_locking_callback
qt.network.ssl: QSslSocket: cannot resolve ERR_free_strings
qt.network.ssl: QSslSocket: cannot resolve EVP_CIPHER_CTX_cleanup
qt.network.ssl: QSslSocket: cannot resolve EVP_CIPHER_CTX_init
qt.network.ssl: QSslSocket: cannot resolve sk_new_null
qt.network.ssl: QSslSocket: cannot resolve sk_push
qt.network.ssl: QSslSocket: cannot resolve sk_free
qt.network.ssl: QSslSocket: cannot resolve sk_num
qt.network.ssl: QSslSocket: cannot resolve sk_pop_free
qt.network.ssl: QSslSocket: cannot resolve sk_value
qt.network.ssl: QSslSocket: cannot resolve SSL_library_init
qt.network.ssl: QSslSocket: cannot resolve SSL_load_error_strings
qt.network.ssl: QSslSocket: cannot resolve SSL_get_ex_new_index
qt.network.ssl: QSslSocket: cannot resolve SSLv3_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv23_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv3_server_method
qt.network.ssl: QSslSocket: cannot resolve SSLv23_server_method
qt.network.ssl: QSslSocket: cannot resolve X509_STORE_CTX_get_chain
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
qt.network.ssl: QSslSocket: cannot resolve SSLeay
qt.network.ssl: Incompatible version of OpenSSL

**Comment by cryptozoidberg** [comment]
@output123  this output comes from QT binaries, there is nothing we can do about that, i guess it's not related to Zano code at all, just internal qt debug information.
Does wallet works now?
