### ISSUE TITLE
20211123 09:26:19 WARN: Can't handle stratum method in payload {"jsonrpc":"2.0","id":5,"result":[]} , basic_string::substr: __pos (which is 2) > this->size() (which is 0)

### ISSUE THREAD

**Issue by mtmtmt123** [hyle-team/zano#310]
I have this in Miner Console is that a problem?
Thank you
20211123 09:26:19 WARN: Can't handle stratum method in payload {"jsonrpc":"2.0","id":5,"result":[]}
, basic_string::substr: __pos (which is 2) > this->size() (which is 0)

And this in Node ( server for mining )
2021-Nov-23 09:28:47.544395 [P2P4]COMMAND_HANDSHAKE invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
But mining works

**Comment by cryptozoidberg** [comment]
Both messages are fine, i guess it's just a scanner attempt to connect to open ports, if you have some troubles with this just re-open this ticket with more technical info
