### ISSUE TITLE
POS Mining Zano Wallet

### ISSUE THREAD

**Issue by mtmtmt123** [hyle-team/zano#312]
Hello, I have Windows. i will try POS 
i have a question about this command
simplewallet --wallet-file <wallet file> --password  --rpc-bind-port=11222 --do-pos-mining

in (wallet file) what i have to write in ? who can i find the wallet file?
Thanks

**Comment by cryptozoidberg** [comment]
@mtmtmt123  I'm having difficulties to understand what is this question about, could you please re-phrase it or simplify?

**Comment by mtmtmt123** [comment]
I do not know what to enter exactly in cmd to start POS and what exactly I should enter with Wallet File. I bought extra 100zano and now does not know how to manage that, the instructions for POW was easy for POS I find nothing accurate

**Comment by mtmtmt123** [comment]
![zano](https://user-images.githubusercontent.com/93097424/143478066-e3511607-adb8-41cc-9703-9f368847472f.jpg)

**Comment by PRavaga** [comment]
You need to point --wallet-file= to the wallet location, for example --wallet-file=mywalletfolder/mywalletname. The whole command should look like simplewallet.exe --wallet-file=mywallet --rpc-bind-port=11222 --do-pos-mining.

**Comment by PRavaga** [comment]
Or just run it in a GUI wallet, you can enable pos mining there in a single click

**Comment by mtmtmt123** [comment]
open zano tool enable staking is all finish and i stake?

**Comment by PRavaga** [comment]
Yeah if I got you right, you need to flip that switch in the GUI wallet to enable staking
![Screenshot 2021-11-25 181717](https://user-images.githubusercontent.com/10805734/143481867-4e9056e4-ca32-4c6c-9a27-715629b2120c.png)

**Comment by mtmtmt123** [comment]
Very usefull i think before you write this, this doesnt enable staking without that commands i write.
Thank you

**Comment by PRavaga** [comment]
Happy to help!
