### ISSUE TITLE
Add command line option to disable price fetching from GUI wallet

### ISSUE THREAD

**Issue by Gigabyted** [hyle-team/zano#315]
I'm a bit concern over my privacy and I don't like having my wallet hitting a price service and doxing myself against it.

It would be great to have an option (either in the interface or command line) to disable that feature.  I know many care about seeing their wallet value into the wallet, but I don't, at least not at the cost of hitting coingecko periodically and telling them that I'm running the Zano wallet. 

Thanks!

**Comment by cryptozoidberg** [comment]
@Gigabyted thank you for this feature request, we would add this into our next sprint!
