### ISSUE TITLE
Sending to an alias and typing upper case characters leads to alias not valid

### ISSUE THREAD

**Issue by Gigabyted** [hyle-team/zano#319]
Someone reported this to me, he said he was trying to send to an alias like this @Gigabyted and it wasn't letting him since it was @gigabyted (lower case 'g')

I believe we should restrict to lower case chars (or convert them to lowercase as we type) if we set the leading char '@' that mark this as an alias.

Small issue but led to some issues between the 2 people that were trading...

**Comment by cryptozoidberg** [comment]
Fixed
