### ISSUE TITLE
Please add a reliable snapshot [request]

### ISSUE THREAD

**Issue by b8engl** [hyle-team/zano#329]
Please add a reliable snapshot, so that is not necessary to download the hole blockchain.

**Comment by cryptozoidberg** [comment]
@b8engl  i believe we have one in sources, does it work for you? 
Or you mean that it's too old?

**Comment by cryptozoidberg** [comment]
@b8engl yes, https://github.com/hyle-team/zano/blob/c5656534c48ef7c956993a6de88ab5b8ca3e05fa/src/common/pre_download.h#L25 that one is not working?

**Comment by b8engl** [comment]
yes, but that link is 80% from the current state. Could you update to a recent block in a future release?

**Comment by cryptozoidberg** [comment]
got it, will do it with upcoming release

**Comment by cryptozoidberg** [comment]
@sowle  close this issue please when finished

**Comment by b8engl** [comment]
awesome, thanks!

**Comment by cryptozoidberg** [comment]
Let's keep it open until we finish it (just as a reminder)

**Comment by cryptozoidberg** [comment]
Fixed
