### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by bpatelTWO** [hyle-team/zano#334]
I made it all the way to step 6 for Linux. (make -j1 daemon simplewallet) and get the following errors.

collect2: error: ld returned 1 exit status
make[3]: *** [src/CMakeFiles/daemon.dir/build.make:108: src/zanod] Error 1
make[2]: *** [CMakeFiles/Makefile2:755: src/CMakeFiles/daemon.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:762: src/CMakeFiles/daemon.dir/rule] Error 2
make: *** [Makefile:370: daemon] Error 2

Any help would be appreciated

**Comment by cryptozoidberg** [comment]
@bpatelTWO  can you please send the whole log of the build? This part doesn't say anything about reason it failed

**Comment by bpatelTWO** [comment]
I refreshed the service and tried again, and exact same results. This time I logged the output and also every step I took in the install. Attached both
[log.txt](https://github.com/hyle-team/zano/files/9578108/log.txt)
[Install Steps.txt](https://github.com/hyle-team/zano/files/9578110/Install.Steps.txt)

**Comment by bpatelTWO** [comment]
Here is also the screen log
[screen.log](https://github.com/hyle-team/zano/files/9578221/screen.log)
