### ISSUE TITLE
Desktop wallet runing issue 

### ISSUE THREAD

**Issue by FB71FB** [hyle-team/zano#335]
Can't run Desktop Wallet after installing on Windows 10 (64)
Log:
2022-Oct-19 12:22:05.184306 [tid:6128] Zano v1.5.0.143[336fac2]
2022-Oct-19 12:22:05.246792 [tid:6128] Loading html from path: C:\Program Files\Zano/html/index.html
2022-Oct-19 12:22:05.275238 [tid:14060] Worker thread is started
2022-Oct-19 12:22:05.275238 [tid:10552] Worker thread is started
repporting of Windows event manager :
Nom de l’application défaillante Zano.exe, version : 0.0.0.0, horodatage : 0x62772a12
Nom du module défaillant : LIBEAY32.dll, version : 1.0.2.3, horodatage : 0x557b2a32
Code d’exception : 0xc0000005
Décalage d’erreur : 0x000000000000ca23
ID du processus défaillant : 0x3dd8
Heure de début de l’application défaillante : 0x01d8e3ad02fdf10e
Chemin d’accès de l’application défaillante : C:\Program Files\Zano\Zano.exe
Chemin d’accès du module défaillant: C:\Program Files\Zano\LIBEAY32.dll
ID de rapport : 228d333c-fa81-45e8-9568-b760b885100a

**Comment by cryptozoidberg** [comment]
@Fourat66  hi, sorry about this issue, quick question: do you have an crashdump file in app folder ?
(could be in C:\Users\<USER NAME>\AppData\Roaming\Zano or in C:\Program Files\Zano\)

**Comment by GroupRevo** [comment]
I had this same issue on Windows 11, I had to replace LIBEAY32.dll version 1.0.2.3 with 1.0.2.21 in order to get the application to launch.

**Comment by cryptozoidberg** [comment]
> I had this same issue on Windows 11, I had to replace LIBEAY32.dll version 1.0.2.3 with 1.0.2.21 in order to get the application to launch.

@GroupRevo  thanks for reporting this issue, we'll fix it in our next release.

**Comment by CaydeIamNot** [comment]
> I had this same issue on Windows 11, I had to replace LIBEAY32.dll version 1.0.2.3 with 1.0.2.21 in order to get the application to launch.

Care to share the file? I am unable to locate it and would love to get the desktop app up and running.

**Comment by CaydeIamNot** [comment]
> version 1.0.2.3 with 1.0.2.21

I managed to find the file on the interweb and now it works like a charm!

**Comment by cryptozoidberg** [comment]
@CaydeIamNot sorry about this issue, at this moment we're having troubles with renewing our certificate for signing Windows build, and this is the main reason we can't rebuild it with the new library. 
So far you can get latest version at this URL: [https://api.zano.org/files/libeay32.dll](https://api.zano.org/files/libeay32.dll)
