### ISSUE TITLE
Create a simple AppImage installer

### ISSUE THREAD

**Issue by kekzploitz** [hyle-team/zano#336]
Onboarding new users should be such a chore, Zano is a great project, yet me and a number of others who have taken an interest have literally been unable to get GUI wallet working.

Fixing this problem is KEY to adoption! lets make it happen, it shouldn't be this hard.

**Comment by sowle** [comment]
refs:
https://en.wikipedia.org/wiki/AppImage
https://manjaro.org/

**Comment by kekzploit** [comment]
refs:
https://en.wikipedia.org/wiki/Arch_Linux

**Comment by cryptozoidberg** [comment]
Fixed
