### ISSUE TITLE
Zano GUI wallet not starting on Ubuntu 22.04.1  LTS

### ISSUE THREAD

**Issue by apophis1329** [hyle-team/zano#338]
Hi,

i was running Zano desktop wallet for a lon g time without issues on Ubuntu  20.04.1 LTS - i have now upgraded to the latest Ubuntu 22.04 .01 LTS - since then i get the below error when trying to start Zano.sh

/nvme/Zano/Zano$ ./Zano.sh
/nvme/Zano/Zano/lib
/nvme/Zano/Zano/lib
Generating icon file: /home/mbay/.local/share/applications/Zano.desktop...
/nvme/Zano/Zano /nvme/Zano/Zano
log channel 'tx_pool' enabled
log channel 'core' enabled
log channel 'core' enabled
log channel 'levin_protocol' enabled
log channel 'p2p' enabled
log channel 'rpc' enabled
log channel 'wallet' enabled
log channel 'wallet' enabled
log channel 'wallet' enabled
log channel 'wallet' enabled
log channel 'rpc_proxy' enabled
log channel 'levin_protocol' enabled
log channel 'p2p' enabled
log channel 'rpc' enabled
log channel 'wallet' enabled
log channel 'levin_protocol' enabled
log channel 'p2p' enabled
log channel 'rpc' enabled
log channel 'wallet' enabled
log channel 'levin_protocol' enabled
log channel 'p2p' enabled
log channel 'rpc' enabled
log channel 'wallet' enabled
log channel 'levin_protocol' enabled
log channel 'p2p' enabled
log channel 'rpc' enabled
log channel 'wallet' enabled
log channel 'levin_protocol' enabled
log channel 'p2p' enabled
log channel 'rpc' enabled
log channel 'wallet' enabled
log channels: core currency_protocol tx_pool p2p wallet  enabled
Qt WebEngine ICU data not found at /home/user/Qt5.11.2/5.11.2/gcc_64/resources. Trying parent directory...
Qt WebEngine ICU data not found at /home/user/Qt5.11.2/5.11.2/gcc_64. Trying application directory...
Installed Qt WebEngine locales directory not found at location /home/user/Qt5.11.2/5.11.2/gcc_64/translations/qtwebengine_locales. Trying application directory...
Qt WebEngine locales directory not found at location /nvme/Zano/Zano/qtwebengine_locales. Trying fallback directory... Translations MAY NOT not be correct.
[0102/161114.086810:WARNING:stack_trace_posix.cc(699)] Failed to open file: /memfd:/.glXXXXXX (deleted)
  Error: Datei oder Verzeichnis nicht gefunden
Qt WebEngine resources not found at /home/user/Qt5.11.2/5.11.2/gcc_64/resources. Trying parent directory...
Qt WebEngine resources not found at /home/user/Qt5.11.2/5.11.2/gcc_64. Trying application directory...
[0102/161114.093370:WARNING:resource_bundle_qt.cpp(115)] locale_file_path.empty() for locale 
Qt WebEngine ICU data not found at /home/user/Qt5.11.2/5.11.2/gcc_64/resources. Trying parent directory...
Qt WebEngine ICU data not found at /home/user/Qt5.11.2/5.11.2/gcc_64. Trying application directory...
Installed Qt WebEngine locales directory not found at location /home/user/Qt5.11.2/5.11.2/gcc_64/translations/qtwebengine_locales. Trying application directory...
Qt WebEngine locales directory not found at location /nvme/Zano/Zano/qtwebengine_locales. Trying fallback directory... Translations MAY NOT not be correct.
Path override failed for key ui::DIR_LOCALES and path '/home/mbay/.QtWebEngineProcess'
Qt WebEngine resources not found at /home/user/Qt5.11.2/5.11.2/gcc_64/resources. Trying parent directory...
Qt WebEngine resources not found at /home/user/Qt5.11.2/5.11.2/gcc_64. Trying application directory...
[0102/161114.115288:WARNING:resource_bundle_qt.cpp(115)] locale_file_path.empty() for locale 
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_num_locks
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_set_id_callback
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_set_locking_callback
qt.network.ssl: QSslSocket: cannot resolve ERR_free_strings
qt.network.ssl: QSslSocket: cannot resolve EVP_CIPHER_CTX_cleanup
qt.network.ssl: QSslSocket: cannot resolve EVP_CIPHER_CTX_init
qt.network.ssl: QSslSocket: cannot resolve sk_new_null
qt.network.ssl: QSslSocket: cannot resolve sk_push
qt.network.ssl: QSslSocket: cannot resolve sk_free
qt.network.ssl: QSslSocket: cannot resolve sk_num
qt.network.ssl: QSslSocket: cannot resolve sk_pop_free
qt.network.ssl: QSslSocket: cannot resolve sk_value
qt.network.ssl: QSslSocket: cannot resolve SSL_library_init
qt.network.ssl: QSslSocket: cannot resolve SSL_load_error_strings
qt.network.ssl: QSslSocket: cannot resolve SSL_get_ex_new_index
qt.network.ssl: QSslSocket: cannot resolve SSLv3_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv23_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv3_server_method
qt.network.ssl: QSslSocket: cannot resolve SSLv23_server_method
qt.network.ssl: QSslSocket: cannot resolve X509_STORE_CTX_get_chain
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
qt.network.ssl: QSslSocket: cannot resolve SSLeay
qt.network.ssl: Incompatible version of OpenSSL
[265723:265745:0102/161114.633764:ERROR:service_manager_context.cc(252)] Attempting to run unsupported native service: /nvme/Zano/Zano/content_renderer.service
[265723:265745:0102/161114.633919:ERROR:service_manager_context.cc(252)] Attempting to run unsupported native service: /nvme/Zano/Zano/content_renderer.service
[265723:265745:0102/161114.633963:ERROR:service_manager_context.cc(252)] Attempting to run unsupported native service: /nvme/Zano/Zano/content_renderer.service
^C

would be great to have a working version ready to download  - thanks for all your great work !

**Comment by cryptozoidberg** [comment]
@apophis1329 thanks for reporting this issue, and sorry for troubles, we'll try to fix it asap.

**Comment by cryptozoidberg** [comment]
Hey @apophis1329 !
We've fixed problem with running on Ubuntu 22.04, you can find latest binary in release
https://github.com/hyle-team/zano/releases/tag/1.5.0.143

Keep in mind this: to run AppImage you might need to install FUSE on your system: 
`sudo apt-get install fuse libfuse2`
you might also need to install xinerama extension for the X C Binding with this command: 
`sudo apt-get install libxcb-xinerama0` 

If issue are still there please re-open this ticket

**Comment by ISickMan** [comment]
Hey @cryptozoidberg  what exactly was the issue and how did you fix it?

**Comment by cryptozoidberg** [comment]
@ISickMan the issue was with libraries linkage in distributed binaries + qtwebengine needed to have sandbox mode disabled to get launched on ubuntu 22.04, at least version of qt that we use at this moment (5.11.2), we decided to use [linuxdeployqt](https://github.com/probonopd/linuxdeployqt) tool to create proper AppDir and then AppImage from it, with some custom launcher wrapper script(to enable sandboxing for qt).
