### ISSUE TITLE
[testnet] Windows 11 security antivirus block Zano as malware

### ISSUE THREAD

**Issue by Andreevsky** [hyle-team/zano#341]
testnet-v1.5.0.144[0c0c287]

Windows 11 22H2 build

To succesfully launch app need to turn off windows security real time protection and add Zano folder to exclusion.

![Windows 11 x64 - VMware Workstation 17 Player (Non](https://user-images.githubusercontent.com/16042035/211157751-53719d24-e68c-4d36-a7c1-fda79ad01787.png)
![Windows 11 x64 - VMware Workstation 17 Player (Non (2)](https://user-images.githubusercontent.com/16042035/211157768-df708025-98b6-4018-8c8d-50db78c0b05e.png)
![Windows 11 x64 - VMware Workstation 17 Player (Non (1)](https://user-images.githubusercontent.com/16042035/211157770-50fc2c4b-19d5-4c39-a409-377dbfcac1d5.png)

**Comment by cryptozoidberg** [comment]
Missing signature due to certificate expiration, will be fixed as soon s we get new cert
