### ISSUE TITLE
[testnet] There is not any message of wrong wallet password

### ISSUE THREAD

**Issue by Andreevsky** [hyle-team/zano#343]
testnet-v1.5.0.144[0c0c287]

https://take.ms/7yxf1

1. Turn on master password
2. Open wallet(s)
3. Close app and open again
4. Reset master password
5. Try wrong wallet password
6. There is not any message of wrong wallet password. Visually nothing  happend when click "open wallet" button with wrong password.

**Comment by SergeyZano** [comment]
Issue Not Present
Verified on Build 2.0.0.313[5342440] TESTNET.
