### ISSUE TITLE
[testnet] Wrong notification text message on wallet create screen

### ISSUE THREAD

**Issue by Andreevsky** [hyle-team/zano#345]
testnet-v1.5.0.144[0c0c287]

Wrong notification text for wrong confirm wallet password

![Windows 10 - VMware Workstation 17 Player (Non-com (1)](https://user-images.githubusercontent.com/16042035/211196593-565289f9-59a7-4611-982f-63a2841e94f3.png)

Correct one must be:
![Zano Wallet App – Figma - Google Chrome 2023-01-08](https://user-images.githubusercontent.com/16042035/211196611-78b4de12-522d-4e33-8810-c49fbb1db0f5.png)

**Comment by SergeyZano** [comment]
Issue Not Present
Verified on Build 2.0.0.313[5342440] TESTNET.
