### ISSUE TITLE
[testnet] Contacts tab is missing in GUI wallet

### ISSUE THREAD

**Issue by Andreevsky** [hyle-team/zano#355]
testnet-v1.5.0.144[0c0c287]

![Windows 10 - VMware Workstation 17 Player (Non-com (13)](https://user-images.githubusercontent.com/16042035/211328917-4a9c6069-d410-4aa2-a653-7e581ee67c60.png)

There is Contacts tab at UI design docs:

![Zano Wallet App – Figma - Google Chrome 2023-01-09](https://user-images.githubusercontent.com/16042035/211328993-ffbbccb1-89b3-469a-b336-93a4b532cb7f.png)

**Comment by cryptozoidberg** [comment]
it's not a bug, contracts will be disabled for the first period of Zarcanum network, we planning to enable it after
