### ISSUE TITLE
[testnet] Transfer alias doesn't work

### ISSUE THREAD

**Issue by Andreevsky** [hyle-team/zano#358]
testnet-v1.5.0.144[0c0c287]

When trying to transfer alias to correct wallet address there is an error. If delete 1 symbol of address it become correct for gui but obviously get an error after trasfer.

[Zano.log](https://github.com/hyle-team/zano/files/10374918/Zano.log)

https://user-images.githubusercontent.com/16042035/211354606-00b6d99f-d5c3-465a-898c-af651cd514ff.mp4

**Comment by NazarUsov** [comment]
@Andreevsky Not found in 1.5.0.144[48f9466] TESTNET
