### ISSUE TITLE
[testnet] Alias text design at history tab doesn't correspond UI design docs

### ISSUE THREAD

**Issue by Andreevsky** [hyle-team/zano#360]
testnet-v1.5.0.144[0c0c287]

![Windows 10 - VMware Workstation 17 Player (Non-com3](https://user-images.githubusercontent.com/16042035/211357403-11a81446-cd01-402d-9f1b-5b72b2eb1327.png)

Alias text design at UI design docs:
![Zano Wallet App – Figma - Google Chrome 2023-01-094](https://user-images.githubusercontent.com/16042035/211357519-b7c5f850-272e-4836-9248-fe8086eb67c1.png)

**Comment by Andreevsky** [comment]
![Zano Wallet App – Figma - Google Chrome 2023-01-09 (3)](https://user-images.githubusercontent.com/16042035/211393322-542f8d96-8f6a-40d0-b43f-349fad728bf5.png)

**Comment by cryptozoidberg** [comment]
@PRavaga  could you please elaborate, is this design for VIP aliases only? or regular aliases should be also in blue frame

**Comment by cryptozoidberg** [comment]
@PRavaga ping

**Comment by PRavaga** [comment]
Highlight reserved for aliases of 5 characters or less
