### ISSUE TITLE
[testnet] Wallet name changed to alias-name after assigning alias

### ISSUE THREAD

**Issue by Andreevsky** [hyle-team/zano#371]
testnet-v1.5.0.144[0c0c287]

![Windows 10 - VMware Workstation 17 Player (Non-com (19)](https://user-images.githubusercontent.com/16042035/211407267-6d1b77fb-c56e-4587-949f-43848de76719.png)

https://user-images.githubusercontent.com/16042035/211406713-e66c8674-255b-430e-a722-fe5371040810.mp4

At UI design wallet name didn't changed:
![Zano Wallet App – Figma - Google Chrome 2023-01-09 (4)](https://user-images.githubusercontent.com/16042035/211406897-4e764076-1f9a-4e79-bb95-52923dd69658.png)

**Comment by cryptozoidberg** [comment]
I personally believe this behaviour coded intentionally some time ago and this is "as designed", while actual designs might not reflect it yet, @PRavaga could you please make this clear how it should be from your perspective

**Comment by PRavaga** [comment]
I kinda like it this way, with alias. Wallet name and location still accessible through settings should user need it. I'll updated the ui sources accordingly, thanks for heads up. If everyone is in agreement on that we can close the issue.
