### ISSUE TITLE
[testnet] There is not any place to look at alias comment in the app

### ISSUE THREAD

**Issue by Andreevsky** [hyle-team/zano#372]
![Windows 10 - VMware Workstation 17 Player (Non-com (20)](https://user-images.githubusercontent.com/16042035/211408036-3adc8db9-62fb-42af-9a29-e00217dd8e01.png)

User can set up and edit alias comment but there is not any place to look at it.
May be UI design issue.

**Comment by cryptozoidberg** [comment]
@PRavaga can you suggest what would be the best for this issue?

**Comment by PRavaga** [comment]
I'd suggest block explorer, since normally you'd go there to look it up, I can update the layout if we have corresponding api method.
