### ISSUE TITLE
Восстановление кошелька

### ISSUE THREAD

**Issue by ehduardcvetkov** [hyle-team/zano#379]
Здравствуйте. Я не могу восстановить кошелёк на своём компьютере.  Кнопки "Select wallet location" и "Create wallet" Не активны. Windows 11 
![F5rQRRJ](https://user-images.githubusercontent.com/20089099/225244574-6432ac11-b8e2-45c2-aa19-41229dc38168.png)
![Xa4ZSOq](https://user-images.githubusercontent.com/20089099/225244580-6996c29a-9eab-458d-b8c8-34fce37807d4.png)

**Comment by cryptozoidberg** [comment]
@ehduardcvetkov  Добрый день, сожалеем что у вас возникли сложности. Уточните пожалуйста, какой у вас установлен билд, собран ли он самостоятельно или это бинарники которые скачаны с сайта?

**Comment by ehduardcvetkov** [comment]
Я пробовал и этот то же. Ничего не меняется.

**Comment by ehduardcvetkov** [comment]
![5LJsZ8d](https://user-images.githubusercontent.com/20089099/225654141-8146b8bb-ed4e-47af-99f8-706b1e3858a5.png)

**Comment by cryptozoidberg** [comment]
Эдуард, хотел уточнить - вот в это поле нужно вставить seed-фразу а не адрес, на картинке почему-то виден просто адрес, это скорее всего является причиной того что кнопки неактивны - они не распознают этот текст как корректную сид фразу

<img width="412" alt="image" src="https://user-images.githubusercontent.com/7261328/225678764-e38f7bdf-cced-4600-8814-9616f6bf640c.png">

**Comment by ehduardcvetkov** [comment]
Да, Вы правы. Но когда я вставляю seed фразу активна только левая кнопка -select wallet location , а мне ведь нужна правая ? create wallet . Или какой файл при клике левой кнопкой мне выбрать ???

**Comment by cryptozoidberg** [comment]
Сначала вы выбираете левой кнопкой путь к файлу, и после этого становится доступна правая кнопка, после нее создается кошелек

**Comment by ehduardcvetkov** [comment]
Хорошо. А какой путь указывать. Кошелёк требует не папку, а файл. Какой ? Zano.exe ?????

**Comment by cryptozoidberg** [comment]
Нужно указать в какой файл сохранить кошелек

**Comment by ehduardcvetkov** [comment]
Это я понял. А в какой файл. Где его взять, расширение и т.д.

**Comment by cryptozoidberg** [comment]
Нужно придумать имя для нового файлв, имя вы придумываете сами для него, расширение можете задать какое хотите, мы намеренно не вводим конкретных расширений для кошелька, что бы только владелец кошелка знал где хранится его файл.

**Comment by ehduardcvetkov** [comment]
Файл создать самому ? И с каким расширением ?

**Comment by ehduardcvetkov** [comment]
Вроде разобрался, спасибо. Вы мне очень помогли.

**Comment by cryptozoidberg** [comment]
@ehduardcvetkov happy to help!
