### ISSUE TITLE
Display of upper limit value of minimum transaction amount in the "Send" field is shown in exponential form

### ISSUE THREAD

**Issue by SergeyZano** [hyle-team/zano#396]
Problem Description:
The upper limit value of the minimum transaction amount in the "Send" field is displayed in exponential form instead of the expected numerical value "0.000000000001". This display leads to confusion and makes it difficult for the user to understand the actual value.

Reproduction Steps:

1. Open the application.
2. Go to the "Send" tab.
3. Fill in the required fields, setting the numerical value in the "Amount" field to "0.000000000001".
4. Click the "Send" button.
5. Pay attention to the "Send" field in the appeared modal window.

**Expected result:**
The upper limit value of the minimum transaction amount in the "Send" field should be displayed as "0.000000000001".

**Actual result:**
Currently, the upper limit value of the minimum transaction amount in the "Send" field is displayed in exponential form as "1e-12".

Additional Information:
**All values ranging from 0.000000000001 to 0.000000999999 fall under this issue**
It is also worth noting that the maximum possible number that can be entered in the "Amount" field consists of 20 characters (from 0.000000000001 to 9999999.999999999999), including the decimal point. Please take this into account when addressing this issue.

Environment:

App Build version: 1.5.1.145[https://github.com/hyle-team/zano/commit/5b2625ab0e325e1a31152b580645f3f7c84dcb77]

Edition Windows 10 Home
Version 22H2
<img width="405" alt="Zano_EKT9qkJGhZ" src="https://github.com/hyle-team/zano/assets/88397837/c852484c-44e2-4a13-9be9-ead67b5171cf">

**Comment by NazarUsov** [comment]
This issue has been resolved along with #398
