### ISSUE TITLE
During the initial installation of the application, the settings indicate that the "scale" value is set to 100%. However, in reality, it is set to 125%.

### ISSUE THREAD

**Issue by SergeyZano** [hyle-team/zano#401]
Steps to Reproduce:

1. Install the application for the first time.
2. Go to the application settings.
3. Observe the value of "scale".

Expected result: In the settings, during the initial installation, the "scale" value should be indicated as 100%, and the actual "scale" value should also be 100%.

Actual result: In the settings, during the initial installation, the "scale" value is specified as 100%, but the actual value is 125%, which does not correspond to the expected value.

Environment:

App Build version: 1.5.1.145[https://github.com/hyle-team/zano/commit/5b2625ab0e325e1a31152b580645f3f7c84dcb77]

Edition Windows 10 Home
Version 22H2

**Comment by NazarUsov** [comment]
Check the logs, if the scale initially comes: 10px, then this problem needs to be solved with the initial settings that come.
