### ISSUE TITLE
Missing Build Version in the Build version field

### ISSUE THREAD

**Issue by SergeyZano** [hyle-team/zano#409]
Problem Description:
The Build version field does not contain the specified build version. The field remains empty or contains an incorrect value that does not correspond to the current version of the application.

Reproduction Steps:

Open the application.
Go to the "Settings" or "About" section.
Pay attention to the Build version field.
Notice that the field does not display the build version or contains an incorrect value.
Expected Behavior:
The Build version field should indicate the current version of the build. This allows users to easily determine which version of the application they are using.

Actual Behavior:
The Build version field does not indicate the build version, making it difficult to identify the current version of the application. This can lead to difficulties in tracking and correlating build information with other users or with data regarding issues specific to a particular version of the application.
![image](https://github.com/hyle-team/zano/assets/88397837/669e31a5-1775-4195-88d9-4a361684e023)
Environment:

Build version: zano-win-x64-cryptoassets-testnet-v2.0.0.208[https://github.com/hyle-team/zano/commit/66cd998f4dedc9fcff0db8bca6730035313b8d6b]

Edition Windows 10 Home
Version 22H2

**Comment by NazarUsov** [comment]
Most likely there was an error in the get_version or get_network_type command and because of this there is no build version. I made it so that if there is an error, there will be the following text There was an error getting the build version

**Comment by SergeyZano** [comment]
Corrected in Build version: 2.0.0.211 [e3f2170] TESTNET.
