### ISSUE TITLE
Incorrect Calculation in the Amount

### ISSUE THREAD

**Issue by SergeyZano** [hyle-team/zano#411]
Description:
Summary: The Amount field is incorrectly including the Fee value in its calculation.

Reproduction Steps:

Launch the application and navigate to the transaction page.
Initiate a new transaction by entering the required details.
Specify an amount for the transaction, ensuring that a Fee value is also provided.
Submit the transaction and observe the calculated Amount value.
Expected Result:
The Amount field should only consider the transaction amount and exclude the Fee value from its calculation. The calculated amount should accurately reflect the entered transaction amount.

Actual Result:
The Amount field is including the Fee value in its calculation, resulting in an incorrect calculated amount. This means that the calculated amount is higher than expected, as it includes the added Fee value.
![image](https://github.com/hyle-team/zano/assets/88397837/5ed4391c-a05a-4038-93a1-927563d47da0)
Environment:

Build version: zano-win-x64-cryptoassets-testnet-v2.0.0.208[https://github.com/hyle-team/zano/commit/66cd998f4dedc9fcff0db8bca6730035313b8d6b]

Edition Windows 10 Home
Version 22H2

**Comment by NazarUsov** [comment]
Such data comes, in the wallet in the history tab there are no recalculations for amount.
