### ISSUE TITLE
 Incorrect Error Message for Transaction Fee Below 0.01

### ISSUE THREAD

**Issue by SergeyZano** [hyle-team/zano#415]
1. Launch the application on any compatible device.
2. Initiate a transaction and set the transaction fee to a value below 0.01 ZANO.
3. Proceed with the transaction by confirming the necessary details.
4. Observe the error message displayed upon attempting to submit the transaction.

Expected result:
When the transaction fee is below 0.01 ZANO, the application should display the error message "Transaction fee below 0.01 ZANO" to notify the user of the minimum fee requirement.

Actual result:
Instead of the expected error message, the application displays "TX REJECTED" when the transaction fee is below 0.01 ZANO. This error message is ambiguous and does not provide the user with clear information about the issue.
![image](https://github.com/hyle-team/zano/assets/88397837/11cb7ddd-77f9-4f4e-bcd8-380473f4adb7)

Environment:

Build version: zano-win-x64-cryptoassets-testnet-v2.0.0.208[https://github.com/hyle-team/zano/commit/66cd998f4dedc9fcff0db8bca6730035313b8d6b]

Edition Windows 10 Home
Version 22H2

**Comment by NazarUsov** [comment]
Build version: 2.0.0.208[1183c8b] TESTNET works correctly

![image](https://github.com/hyle-team/zano/assets/45450850/523dc694-9758-4064-b6a9-1145f5a71441)

**Comment by SergeyZano** [comment]
Corrected in Build version: 2.0.0.211 [e3f2170] TESTNET.
