### ISSUE TITLE
zano wallet service returns empty seed value in plain_wallet::generate

### ISSUE THREAD

**Issue by LeoBlackCat** [hyle-team/zano#435]
On an Android device the Zano mobile wallet service returns an empty seed value in response to 'plain_wallet::generate' on the testnet. 
Later, after syncing we can get valid seed in wi_extended structure in wallet_info.

[create_wallet_result.json](https://github.com/hyle-team/zano/files/14667503/create_wallet_result.json)

**Comment by cryptozoidberg** [comment]
Fixed
