### ISSUE TITLE
No staking rewards

### ISSUE THREAD

**Issue by cineblockfounder** [hyle-team/zano#439]
Before I was receiving staking rewards on the regular, but now nothing. I downloaded the most recent app release and installed. Is there something I'm missing?

**Comment by cryptozoidberg** [comment]
@cineblockfounder  hi, sorry about the issue, after the hardfork you have to move all your funds to newly created wallet(probably with few transactions), and then after it all confirmed you may return it back to old wallet (or keep on the new), after that staking should work same as it was before. We apologise for this inconvenience, we still working on the new version of the wallet that would fix this issue with one-click solution, it now in develop branch and would be ready in a week or so. 
Let me know if it worked

**Comment by cryptozoidberg** [comment]
Closing the issue, if problems is still present don't hesitate to re-open it and tag me. @cineblockfounder
