### ISSUE TITLE
getblocktemplate does not return valid json object anymore

### ISSUE THREAD

**Issue by pinpins** [hyle-team/zano#440]
See below example

`{
  "id": 0,
  "jsonrpc": "2.0",
  "result": {
    "block_reward": 1000000000000,
    "block_reward_without_fee": 1000000000000,
    "blocktemplate_blob": "0300000000000000000ffa76537e7d30e7f97f913088d0716415c9474eba4bb128718268cf223060010087d9fdb20600020100dec5a2010516fdb4289dc24d52d3050aecf1d76f9a4426cf340ec780b29ccb04ed40c3ec6e7715000b02566c0b02c3b90ee8c5a2010226e2ec7028cbe8df19c10b6969bca5d6295e9fd850aea781c3df36281db2d7493baadfb7f5337ceed98c28e8562a7b03363e298d0fa8249e5d31a7a23dab5c6fe796f19195f905378c347b3e15d880665556adae8e7e3ef8cec87dee4ddcebe35a74c32d3eaafafc623bf483e858d42e8bf4ec7df064ada2e34934469cff6b62686f7e25e3b427d2fb0026b73942e511e1bc61d7febcbeaa9e7f7e8db9592f3a0d11b0c7a07b00b99a51043267e7d222a957e2dee34b6b539803a9c7ed4fb081e2e6b8de593bd97008ba1270048c4caea264b9045a53c557b5b13f1c2e8240b10e9cef33d77ddd5dc4683c74c32d3eaafafc623bf483e858d42e8bf4ec7df064ada2e34934469cff6b62688ca39a460c87be1d000000032e002f07f9436515751815f31479d94fbf1f245fcf27a0a774ce5b9ab0bd22efc69d243e7b1c6d6d66fc1c20f83e263723b0a12ec531e5dda1c77865ac98aabc456f21d080ad9b35ffa1984ef6b681942c1f2a037551eb122ebdbc36cf3ae1b4b9e0837f22e29730d6c77bd2f200f336e7c482620e374159ccc92002bc9ed3356912be521db187cff8017ee70bfe74812b246a58532905a762eb7f8db43e0978f42cb92cd1636aaf656a8475f3fc4b1395177ba7ebbd7987fb4819155d1930f0630d3ba88c7b22668b51cbee00eeda659f2702d7b5b47605664ea16e7ed478b016c661740773afe09ef2abb89275346dc7f680aa24241846d8612d2fc9d225fe17b3420c8ac4b93384eb1f2426156d44a8c6ca7e70fe5f7ac7af3e705e6b25a91f93a78e4986493ee287c6b6709426f99ed5f706f5aabec61bc2e748d00e1dafcad068f03273533ad95e1d71dc4b9f477cbc66a344d8bf38e6bc87e23848015761f39fedac954efe990af9166177aad36591e5b83dc2f3e4b9dae981bb1d4f7adb4d53f20d27073d83a3193954d008a59214248dc9429a778c3843500301a66cef706b9eb507ccc2532590bdb6b9d08a941bb39814721efdf2e746cab4c786ba39f334036bc6fc5262952a9ff353145b0529c3ae3978e8bc7a64210cfcef8a5ed472db32be4f6b508cc9faf2d5289ba38b0e84ed2862ebf4653bae21c1bb95580898094a667cbdea8855f8206574ff6bec0dfb9686aefbb2dbea89820fe228c08fb723dc51ad75088534994ca3a50215627b54a9ed461aad857fb1a4f270e3db367c4b5806b8e3ccc4c1d73c15922a8702c818bdd4ba457f3bc94d7700b09ef2189affba0d69a4069cd9d7916a5ba9f3ee320b72c83c9ecbdbcc98df23b36902d940c4dc0e02577e3a56af1b9885b1dd4670b974beb75b665ca6743b913c0b93e3c9625f266cce81ac77a8814b02c2a829ae6de43571a712a5eec12de36adafd9f205e2cf994024879ec84830995ace1d234183d1a6077ab1428a25e5a2bd0a589887306f5900a249bb2023d8cb7f4327752fecc7a7fc7b6aba914c429637dc3e1a0a0b930b20502855840c5199c28107d56bc6fd92fa5885f6ff3a693be23e5c2a9e50a09d056072c3329df0bb8ea1a2cf4f96e9b7edd2388926c165e44a2d749459fe8e163460c484ed8c5da29ce72e110020d3fd757635d15829c119b2e4dcf39e707170e580f30b862868102f0bf98e90e1b815ec7e3afaf1f1701055ae29ea00a01843f2eda0b4005ae50a88e06ffe5f176223956c6e8b9914e0148c1ea6dd92305949b7f800c71d75726818383e743dd0eccb84aff747e9271bf39e8eea6a958fe9087e4c20500",
    "difficulty": "10345864503908",
    "height": 2663134,
    "miner_tx_tgc": {
      "amount_blinding_masks": "�7�iò]\u0005V��8�]e���_�IѪ�\u0010\u0016�`��\u0004�?����m`�9��e�����p��$�2G��=��\u000b",
      "amount_blinding_masks_sum": "d8a376f289d7b80d3127acd4bfa33c07afac87d06220f645cc57af449e9f5000",
      "amount_commitments": "�\u001c�\u0001�\u0019�\u0000.!;��\b&\u0000?�b�B�\u0019\u0000x�'�� 8\u0000��g\u0000�H�\u0000\u001b\u001a&\u0000���\u0000XY���B���\b}\u0001²p\u0000�|�\u0000�>��<\u0011;��`*\u0000���kg�\u0000�\u001c�\u0000��4\u0000q?\u001d\u0001\u001f��� c\u000b���\u0004�R��\u0001�I#\u0000s���']�\u0000I�g��+�L�\u001c�� {\u0000�i���&D\u0000�A��(������\u0000��\u0001�Ԙ��� �\u0000�r~\u0001\u0003��\u0000;�-���\u001e�\u0006�[�����^����l�\u0000�e��̻��%�*\u0001\u0007�]\u0000Ƀ��å�\u0000�ʵ��#i\u0000�'�������\u0005���;c��\u001bf��z\u0010\u0000#���\u0015x��\/g�q ��b��\u0001o�N�\u000bX�\u0000\u0002��\u00007.8\u0001�5\u001d�\nF ����\u0000�0�\u0000����",
      "amount_commitments_sum": "c8c55300a3b930ff64ae1300b25137ffa9a2edfe04529400648b5800d59eebffbf78b0ffe4fd0b004b261aff1d0a83ffcbb94e01e9e8af0008c6bb00c7b32b0050b47800e4124900d3530901ee4c9cff219e25ff7cad5fff4b9d4c00af5ddfff3f319401b64f76ffeb79f00194a4efffe8b6c2013884ef00f3db4f015ad9da007bf6f2009a5dd0002df07dff4b1d25ff15e05a01a43322ff8a246c00ba2cbe00",
      "amounts": "\u0000�8�\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\"\u0011�g\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000",
      "ao_amount_blinding_mask": "0000000000000000000000000000000000000000000000000000000000000000",
      "ao_amount_commitment": "00000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
      "ao_asset_id": "0000000000000000000000000000000000000000000000000000000000000000",
      "ao_asset_id_pt": "00000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
      "ao_commitment_in_outputs": "00",
      "asset_id_blinding_mask_x_amount_sum": "0000000000000000000000000000000000000000000000000000000000000000",
      "asset_id_blinding_masks": "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000",
      "asset_ids": "\u0000���?_��\u000f\bn��~����V\u0001�Q�\u00002\u0002\u001f\u0001\u001b���Y\u0018\u0000�G���2���\u0007\u001f\u0000��v\u0000.��\u0000�Q\u0001\u0000*\/U\u0000�\"��ʮH�\u000e\u000e\u001e\u0001�&)\u0000\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000�\u0005�\u0000g0\/\u0000��0\u0000\u0016\n~�!�'�d��\u0000s\u0014�\u0001r�\u001e�y�2\u0000���\u0000\u0000���?_��\u000f\bn��~����V\u0001�Q�\u00002\u0002\u001f\u0001\u001b���Y\u0018\u0000�G���2���\u0007\u001f\u0000��v\u0000.��\u0000�Q\u0001\u0000*\/U\u0000�\"��ʮH�\u000e\u000e\u001e\u0001�&)\u0000\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000�\u0005�\u0000g0\/\u0000��0\u0000\u0016\n~�!�'�d��\u0000s\u0014�\u0001r�\u001e�y�2\u0000���\u0000",
      "blinded_asset_ids": "���\u0007�s\u0000����\u0011C�\u0000\u001b�#\u0001\u001cB>\u0000��F\u0001y\u0004���ރ\u0000ȴ��ݩ\u0010�\u0007�W\u0000�\u0013�\u0001�B�\u0000w\u001d'����YQ�\u0001��t�\u0005GH\u0000�\rD��\u0004;\u0000\u0007lr�\nX\t��d\u000e\u0000={��\u0005Rc��n���,�\u0000��c\u0001ߚp\u0000\u001d=��\u0007\f�\u0000����k��\u0000��A\u0001��������q����Є�c|�����\u0007�s\u0000����\u0011C�\u0000\u001b�#\u0001\u001cB>\u0000��F\u0001y\u0004���ރ\u0000ȴ��ݩ\u0010�\u0007�W\u0000�\u0013�\u0001�B�\u0000w\u001d'����YQ�\u0001��t�\u0005GH\u0000�\rD��\u0004;\u0000\u0007lr�\nX\t��d\u000e\u0000={��\u0005Rc��n���,�\u0000��c\u0001ߚp\u0000\u001d=��\u0007\f�\u0000����k��\u0000��A\u0001��������q����Є�c|��",
      "pseudo_out_amount_blinding_masks_sum": "0000000000000000000000000000000000000000000000000000000000000000",
      "pseudo_out_amount_commitments_sum": "00000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
      "real_in_asset_id_blinding_mask_x_amount_sum": "0000000000000000000000000000000000000000000000000000000000000000",
      "tx_key": "fdb4289dc24d52d3050aecf1d76f9a4426cf340ec780b29ccb04ed40c3ec6e77fd50bd95346945443947a6f123a862f52e1409d7713628f682e98f4fcb23da01",
      "tx_pub_key_p": "412d81ff98457300acaf34fe83483800512bf1fe0f0671004700e9ff36bf3b008077770116373aff10b52801a77093006aba4001608fbf00bf69120126cf34008763400196739900d00e3400b3bbddff010000000000000000000000000000000000000000000000000000000000000000000000000000009259610016a1d9ffc2d091fe61d078fff673f6014c980cfff6fd74fe616c93006f6015ffc5015600"
},
    "prev_hash": "0ffa76537e7d30e7f97f913088d0716415c9474eba4bb128718268cf22306001",
    "seed": "9336adfd9667a72451ef339e888c4053d10c735d612950f05fbe22d9a139e54c",
    "status": "OK",
    "txs_fee": 0
}`

**Comment by cryptozoidberg** [comment]
@sowle can you take a look at this?

**Comment by sowle** [comment]
fixed in c21785add4a618f46f23fa690f6a9867472e977f
