### ISSUE TITLE
FEATURE REQUEST: Upon opening the Zano Desktop wallet, remember my last known Staking values  ON/OFF

### ISSUE THREAD

**Issue by mvozzo** [hyle-team/zano#446]
When I open the Zano Desktop GUI Wallet, some of my wallets have "Staking = ON" and others do not. 
I'd like for Zano Desktop Wallet to remember these settings in the event I close the wallet and open it later.

If this is not possible, then please add an option to the "Settings" page that allows users to select which wallet that would like "Staking = ON" when opening their Zano wallet. 

This will be a nice feature to see and will save a users time and a much better user experience.

**Comment by cryptozoidberg** [comment]
@SergeyZano can you double check behaviour of this feature? 
I think it's stored in state of the UI config if you have master password. @mvozzo  are you using master password?

**Comment by mvozzo** [comment]
Hi @cryptozoidberg , Can you please clarify whether Wallet Password is the same as a Master Password?
When I open Zano Desktop GUI, I am prompted to enter a Password to each of my Zano wallets before the GUI is unlocked to display my balances etc. If this is indeed the same as a "Master Password" then I can confirm they I do have it set.

**Comment by PRavaga** [comment]
Check out this article https://docs.zano.org/docs/use/zano-passwords

**Comment by mvozzo** [comment]
Thanks @PRavaga for the link on the different passwords. 
I can confirm that once I've setup a Master password the Wallet Auto locks and when I log back in, staking is still on. 
I have also tested closing the wallet down and then opening the wallet up. The wallet prompts me for my Master password.  Upon successful login I can see that "Staking" = On. 

So, all in all, this feature already exists and I just had not setup a Master Password to enable it. 

Thanks for your help PRavaga.

**Comment by mvozzo** [comment]
Well Done Zano Team!   This feature already exists when using a Master Password.   
My issue was lack of knowledge about the different types of passwords.  

May I suggest have an information bubble or link to this web article ( https://docs.zano.org/docs/use/zano-passwords ) from within the GUI Wallet so that users know what the benefits of setting a Master Password are.
