### ISSUE TITLE
P2P error (just for info)

### ISSUE THREAD

**Issue by toptim** [hyle-team/zano#45]
`[P2P5]Timeout on invoke operation happened, command: 1002
[P2P5]BACKTRACE: 

STACK
~/zano/build/release/src/zanod() [0x528fea]
~/zano/build/release/src/zanod(_ZN5boost4asio6detail12wait_handlerIZN4epee5levin22async_protocol_handlerIN8nodetool24p2p_connection_context_tIN8currency27currency_connection_contextEEEE14invoke_handlerIZNS3_9net_utils28async_invoke_remote_command2INS6_20COMMAND_TIMED_SYNC_TINS8_14CORE_SYNC_DATAEE8responseENSH_7requestEZNS6_11node_serverINS8_27t_currency_protocol_handlerINS8_4coreEEEE18do_peer_timed_syncERKNSD_23connection_context_baseEmEUliRKSI_RSA_E_NS4_29async_protocol_handler_configISA_EEEEbNS_5uuids4uuidEiRKT0_RT2_RKT1_mEUliRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESU_E_EC4ERKS1G_mRSB_iEUlRKNS_6system10error_codeEE_E11do_completeEPNS1_15task_io_serviceEPNS1_25task_io_service_operationES1O_m+0x1de) [0x54f1be]
~/build/release/src/zanod(_ZN4epee9net_utils18boosted_tcp_serverINS_5levin22async_protocol_handlerIN8nodetool24p2p_connection_context_tIN8currency27currency_connection_contextEEEEEE13worker_threadEv+0x81e) [0x52356e]
/usr/lib/x86_64-linux-gnu/libboost_thread.so.1.58.0(+0x115d5) [0x7fca5de775d5]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7fca5e4af6ba]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7fca5c51b41d]

[P2P5]Failed to invoke command 1002 return code -4(LEVIN_ERROR_CONNECTION_TIMEDOUT)context:188.32.136.195:55997 5498e179-df63-452a-91c9-2f5ba51a7791 INC
2019-Jul-23 07:07:13.453472 [P2P5]BACKTRACE: 

STACK
~/zano/build/release/src/zanod() [0x528fea]
~/zano/build/release/src/zanod() [0x58a1ab]
~/zano/build/release/src/zanod() [0x542d8a]
~/zano/build/release/src/zanod() [0x5430ee]
~/zano/build/release/src/zanod() [0x5431d8]
~/zano/build/release/src/zanod(_ZN5boost4asio6detail12wait_handlerIZN4epee5levin22async_protocol_handlerIN8nodetool24p2p_connection_context_tIN8currency27currency_connection_contextEEEE14invoke_handlerIZNS3_9net_utils28async_invoke_remote_command2INS6_20COMMAND_TIMED_SYNC_TINS8_14CORE_SYNC_DATAEE8responseENSH_7requestEZNS6_11node_serverINS8_27t_currency_protocol_handlerINS8_4coreEEEE18do_peer_timed_syncERKNSD_23connection_context_baseEmEUliRKSI_RSA_E_NS4_29async_protocol_handler_configISA_EEEEbNS_5uuids4uuidEiRKT0_RT2_RKT1_mEUliRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESU_E_EC4ERKS1G_mRSB_iEUlRKNS_6system10error_codeEE_E11do_completeEPNS1_15task_io_serviceEPNS1_25task_io_service_operationES1O_m+0x200) [0x54f1e0]
~/build/release/src/zanod(_ZN4epee9net_utils18boosted_tcp_serverINS_5levin22async_protocol_handlerIN8nodetool24p2p_connection_context_tIN8currency27currency_connection_contextEEEEEE13worker_threadEv+0x81e) [0x52356e]
/usr/lib/x86_64-linux-gnu/libboost_thread.so.1.58.0(+0x115d5) [0x7fca5de775d5]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7fca5e4af6ba]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7fca5c51b41d]

[P2P5]Failed to invoke command 1002 return code -3(LEVIN_ERROR_CONNECTION_DESTROYED)context:188.32.136.195:55997 5498e179-df63-452a-91c9-2f5ba51a7791 INC`

**Comment by zano-shit-coin** [comment]
They even do not have the ability to save the password well for user after six months development.
What can you expect from them?

**Comment by cryptozoidberg** [comment]
Thanks for reporting this, basically this situation is not supposed to be decorated this dramatical way with call stacks and stuff since this is a pretty common situation in p2p network, we have this type of errors enabled just to be able to notice some potential problems inside the daemon, such deadlocks or freezes. Are you still keep getting this errors or it was just an accidental?

**Comment by toptim** [comment]
see it time to time

**Comment by cryptozoidberg** [comment]
Another question - you seeing it always to the same ip? (context:188.32.136.195) or is it different ones? Internet connection is stable?

**Comment by toptim** [comment]
only with this ip:
93.123.65.11
154.221.18.75
how i can block it zano.conf?
