### ISSUE TITLE
Balance amount displays wrong after accepting contract

### ISSUE THREAD

**Issue by Andreevsky** [hyle-team/zano#47]
**Description**
Create contract '11' and accept it.

For the few seconds overall balance displays wrong. After that it updates for correct values. (Values was 4000.xxx instead of 2000.xxx)

https://take.ms/6ig9B

 
This bug was noticed on main net also. 
It reproduces sometimes, not any time.

May be depends on outputs available on wallet.
 

Notice that balance updates to correct after first confirmation.

**Attachments**
[zano-394.zip](https://github.com/hyle-team/zano/files/3436064/zano-394.zip)

**Environment**
> zano-win-x64-release-testnet-v1.0.36[17ef2dd]

> win10

**Comment by Andreevsky** [comment]
> Create contract '11' and accept it.
> 
> For the few seconds overall balance displays wrong. After that it updates for correct values. (Values was 4000.xxx instead of 2000.xxx)
> 
> https://take.ms/6ig9B
> 
>  
> This bug was noticed on main net also. 
> It reproduces sometimes, not any time.
> 
> May be depends on outputs available on wallet.
>  
> 
> Notice that balance updates to correct after first confirmation.
> 
> [zano-394.zip](https://github.com/hyle-team/zano/files/3436064/zano-394.zip)

comment from wmc:
Backend problem: frontend only displays the data that comes in.
Here is a signal from a log file where the balance is 4000,143 (log_balance_4000.json). After 5 seconds the signal with the balance of 2000,143 (log_balance_2000.json)

**Comment by Andreevsky** [comment]
_bug still exist at build v1.1.2.67[88f868c]_

1. at wallet "ZxC9ui9sRwiaWsEU4nbJXuef7wCn8TqGXLxDvbVJKupA6XhkxBZxtq28AtuBAJ5bUxTMNTc5f1YkMHoAM14evJJu1bXvfzE7k" was 0.141
2. created contract "v67 test" with 0.02 amount. balance after contract proposal and first confirmation was ok. (0.131)
3. accepted contract. **balance displayed became wrong = 0.141**. only after first confirmation balance became correct (0.111)
id:
001e1b3a59ebffcdcffa1f159aa541963900636bf1fdde34120d827b7c33d794

[Zano.log](https://github.com/hyle-team/zano/files/3728982/Zano.log)

**Comment by sowle** [comment]
Should be fixed in 1.1.3.69
