### ISSUE TITLE
Unaligned memory access in block validation, likely causing segfaults and slowness

### ISSUE THREAD

**Issue by jeffro256** [hyle-team/zano#482]
This snippet of code technically causes undefined behavior, since it breaks the strict aliasing rule, and practically speaking will likely cause segfaults on ARM processors. It will also practically impose heavy costs on memory access in x86, where unaligned memory access is allowed, but destroys performance. 

https://github.com/hyle-team/zano/blob/2817090c8ac7639d6f697d00fc8bcba2b3681d90/src/currency_core/basic_pow_helpers.h#L37-L45

Fix: Set the nonce to 0s using a `char*` and `memset` like the string that it is, and don't try weird integer pointer punting tricks to modify 8 bytes worth of memory.

**Comment by jeffro256** [comment]
Here's a short summary article about unaligned memory access on ARM: https://medium.com/@iLevex/the-curious-case-of-unaligned-access-on-arm-5dd0ebe24965. Sometimes it works with performance hits, sometimes it causes a segfault, and sometimes it silently rounds the address by ignoring the LSBs. The behavior depends on which version of the ARM architecture and whether or not some CPU flags are set.

**Comment by cryptozoidberg** [comment]
@jeffro256  thanks for pointing to this issue, we've fixed this particular functions but i believe that there might be few more in the codebase, on a rare occasions i used this hacky way of patching memory, guilty as charged, never could imagine that random access to legitimate memory might lead to seg fault. We'll be looking into the code base to get rid of such artefacts
