### ISSUE TITLE
Proposal: Remove stuck transactions with keyimages conflicts

### ISSUE THREAD

**Issue by Andreevsky** [hyle-team/zano#52]
In some situations possible that transactions got stuck in tx pools (for example last PoS mining problem on simplewallet, when simplewallet was not tracking new transactions came from it's copy in other machine)

Need to figure out a policy which let this type of transactions get dropped from tx pool after a certain amount of confirmation in blockchain. 
@sowle  Need your thoughts.

**Comment by Andreevsky** [comment]
sowle:
We can look for spent key images in the blockchain and if the corresponding block is deep enough (say, 50 blocks) – drop txs with the same key images from the pool.

**Comment by Andreevsky** [comment]
zoidberg:
Agree

**Comment by sowle** [comment]
Added a test for this issue: e9bc068bfb64b4fcbade957084849bffffc1b0b5
