### ISSUE TITLE
App not responding after strating

### ISSUE THREAD

**Issue by Andreevsky** [hyle-team/zano#55]
**Description**
https://take.ms/KMtiq

 
App was started, after entering master password  not responding for a minute.

Before that, PC was in sleep mode. After waking up, app was closed and than started and this bug appears.

 
Bug repeats for second time also:

https://take.ms/VBlWS

**Attachments**
[227.zip](https://github.com/hyle-team/zano/files/3436431/227.zip)

**Environment**

> zano-win-x64-v1.0.9[43faf7d]
> windows 10 1803

**Comment by Andreevsky** [comment]
sowle:
Artemy please, try to reproduce this issue in build 39

**Comment by Andreevsky** [comment]
v39 works wellm can't reproduce.

**Comment by Andreevsky** [comment]
Issue exists when pc long time in sleep mode (6hr+ probably), doesn't reproduces if go to sleep mode and restore after few minutes.

(zano-406 similar case)

**Comment by cryptozoidberg** [comment]
According to logs this problem is related to QTWebEngine, let's hope that new version won't crash. If it still crashing then re-open this ticket and generate a crash report and send it to qt.
