### ISSUE TITLE
White screen issue after sleep mode

### ISSUE THREAD

**Issue by Andreevsky** [hyle-team/zano#56]
**Description**
After long time sleep mode with Zano app runnning there is an issue with white screen. After killing processes (qtwebengine also) posible to run app again.

Log included. (from Jed)

https://drive.google.com/file/d/1TeBml8PoyDwjqMSe1BDIVes1TS3DwyD7/view

 

Short time sleep mode doesn't affect this, probably only long time enough cause this bug.

**Attachments**
[406.zip](https://github.com/hyle-team/zano/files/3436488/406.zip)

**Environment**

> win 10 1803
> 
>  2x 1080ti GPU, but mining was off 
> 
>  https://cdn.discordapp.com/attachments/567762812944908317/590939230012702720/unknown.png
> 
> spec of two systems:
> 
> https://cdn.discordapp.com/attachments/567762812944908317/590939824933044254/unknown.png

**Comment by Andreevsky** [comment]
here is another log file:
https://drive.google.com/file/d/1x54dtDRt0r28S2g6OWRyjzYldySUHnhz/view

 

PC was in sleep mode 1h+ with app launched, then after waking up and closing wallet it  would not start and would crash as soon as process started, had to restart pc to get it to work again.

**Comment by Andreevsky** [comment]
If sleep 25 minutes, then waking up, app syncing with network, works well. So issue must be from 25 minutes to 1h+ of sleep mode.

**Comment by Andreevsky** [comment]
On my PC can't reproduce this issue.

Was running testnet v40 app and sleep mode for 2hr. After wake app blockchain sync well and pos start, transactions confirming.

If may be need to compare, add log file.

**Comment by cryptozoidberg** [comment]
Obviously problem related to qtwebengine, if we face it again - let's write a report to qt.
