### ISSUE TITLE
Wallet data integrity when the drive is full (add write operations error handling and user notifications)

### ISSUE THREAD

**Issue by Andreevsky** [hyle-team/zano#57]
Artemy please test wallet's integrity when the drive it's located become full and no free space left.
Seems the wallet may become corrupted, need more research from you.
Ideally step-by-step manual on how to reproduce the issue (if it exists).

**Comment by Andreevsky** [comment]
Wallet file become corrupted and then automaticaly restore using seed phrase.

I open wallet file of 457kb size that wasn't full synced (full size must be 5098kb) on a drive with 608kb left space. It work well. Then I close it. It close fast without any error.

Data was recorded on drive where wallet located until 0 bytes free space left.

After next run at application got error:

https://take.ms/6xB4e

After clicking "ok" wallet was restored and work well. Restored wallet file recorded sucessfully on drive (I clean free space for it).

 

log included and wallet file (not synced, corrupted, and restored) (pass 111)

[408.zip](https://github.com/hyle-team/zano/files/3436586/408.zip)

**Comment by Andreevsky** [comment]
zoidberg:
I think we need to handle errors on write operations during store wallet and make some message about this problem in GUI or simplewallet.

**Comment by sowle** [comment]
@Andreevsky seems fixed, make sure it's okay, please

**Comment by sowle** [comment]
This is how error message about not enough space on wallet save/load looks like now:
![image](https://user-images.githubusercontent.com/29127158/66758032-2688eb80-eea6-11e9-868f-0f66e8fa1297.png)
