### ISSUE TITLE
Testnet build don't sync with network

### ISSUE THREAD

**Issue by Andreevsky** [hyle-team/zano#58]
I try to clean install testnet build.

Sync stopped at 36.96% and don't continue. Blinking scale and offline at gui.

log included.

https://take.ms/b8bAg

[Zano_testnet.zip](https://github.com/hyle-team/zano/files/3436596/Zano_testnet.zip)

**Environment**
> zano-win-x64-develop-testnet-v1.0.39[8245ea6]
> 
> win 10

**Comment by Andreevsky** [comment]
Old, partially synced blockchain synced succesfully, so bug only with new sync from zero.
reproduce it - sync stop again
https://take.ms/vKnEe

**Comment by sowle** [comment]
Testnet build seems to be okay with syncing
