### ISSUE TITLE
Expiration time calculation is wrong

### ISSUE THREAD

**Issue by Andreevsky** [hyle-team/zano#60]
**Description**
Was created contract "more test cancellinf expire"

Was made cancellation of contract with expire time 5h. 

https://take.ms/u2BK8
 

After 12h buttons for seller is still active. But contract must have already deny cancelling status.

https://take.ms/uB4av

 
tx id:

8ba5f7a5a0d2d2830b8a22b0a0f46e4f1ef122435c2a77660a776ce679066e3e

 
wallets pass "111"

**Environment**

> zano-win-x64-v1.0.16[6702b53]

**Attachments**
[302.zip](https://github.com/hyle-team/zano/files/3436623/302.zip)

**Comment by Andreevsky** [comment]
after more +8h (total 12 +8) correct screen and status displayed:
https://take.ms/nRAXI

https://take.ms/cLtN1
 
add newer log.

**Comment by sowle** [comment]
It seems the issue was fixed on the front end.
When answer time for a cancellation request is over answer buttons disappear even if a user takes no action.
See also `cancel proposal expiration` message in the log with log level 1.

**Comment by Andreevsky** [comment]
already fixed
