### ISSUE TITLE
Error when canceling contract

### ISSUE THREAD

**Issue by Andreevsky** [hyle-team/zano#63]
v1.0.16[6702b53]

https://take.ms/7httT

https://take.ms/JHn3Q

 When buyer clicking button "cancel contract" there is an error.

contract called "b53_2"

 

v1.0.16[f79e993] 

https://take.ms/RIv8a

Same bug.

Error when cancelling contract with 0 (zero) seller's deposit

contract "cancel contract bug 993"

tx id:

971c595dd4b6f44aaf268613bada994883929cb394321441d1d6029d76cc599d

 

wallets included "pass 111"

and also log

**Attachments**
[276.zip](https://github.com/hyle-team/zano/files/3436712/276.zip)

**Comment by Andreevsky** [comment]
also other contract canceling well.

https://take.ms/0pMwx

 

I think may be bug because of 0 amount of seller's deposit:

https://take.ms/LEerW

**Comment by Andreevsky** [comment]
https://jira.hyle.io/browse/ZANO-392

thats another ticket for that issue (still exist at v39 release)

**Comment by sowle** [comment]
```
[tools::wallet2::get_needed_money] @ C:\dev\zano\src\wallet\wallet2.cpp:3037 Message:
0 == dt.amount. THROW EXCEPTION: error::zero_destination
```
This was caused to zero amount in contract, that is now forbidden. Fixed quite a long time ago.
@Andreevsky, please, make sure it's ok

**Comment by Andreevsky** [comment]
already fixed
