### ISSUE TITLE
Error when accepting contract with 0 deposit

### ISSUE THREAD

**Issue by Andreevsky** [hyle-team/zano#64]
**Description**
https://take.ms/PzMri

 
If sellers deposit is 0, there is an error when accepting contract.

contract "17-6" (0 amount, 0 buyer's deposit, 0 seller's deposit)

contract "17-7" (0 amount, 1 buyer's deposit, 0 seller's deposit)
 

accept contract work well, if:

(0 amount, 1 buyer's deposit, 1 seller's deposit)

(0 amount, 0 buyer's deposit, 1 seller's deposit)

(1 amount, 1 buyer's deposit, 0 seller's deposit)

(1 amount, 1 buyer's deposit, 0 seller's deposit)

(0 amount, 0 buyer's deposit, 1 seller's deposit)

 
Error when ask for cancelling contract:

https://take.ms/z8ozv

 
contract "17-9" (0 amount, 0 buyer's deposit, 1 seller's deposit)

contract "17-10" (1 amount, 1 buyer's deposit, 0 seller's deposit)

**Environment**
zano-win-x64-v1.0.17[5b9677e]

**Attachments**
[305.zip](https://github.com/hyle-team/zano/files/3436730/305.zip)

**Comment by sowle** [comment]
@Andreevsky 17-9 case seems to be okay now
17-10 case is covered by #65, please check it in build 41

**Comment by Andreevsky** [comment]
v1.0.43[30e967b] fixed
