### ISSUE TITLE
Application doesn't remember window size after full-screen mode

### ISSUE THREAD

**Issue by Andreevsky** [hyle-team/zano#75]
https://take.ms/0SAof

 
If change for full screen mode and close application window doesn't remember it size after relaunch.

If not use full-screen window size work well.

zano-win-x64-v1.0.17[5b9677e]
[303.log](https://github.com/hyle-team/zano/files/3441376/303.log)

**Comment by cryptozoidberg** [comment]
Seems that nobody care about this issue. Me neither.
