### ISSUE TITLE
Daemon crash at start

### ISSUE THREAD

**Issue by Andreevsky** [hyle-team/zano#87]
User PushiPishu had issue. He got working Zano on one PC, moved appdata to another and got "fatal error" after start of the daemon.
Also Zano wallet just dissapeared after 2-10s after launch if running Zano without copying blockchain files.

spec of the PC where application crushed:
Intel® Core™2 Quad Processor Q8200
4GB RAM _(was 2 GB first, but then app continue to crush with 4 gb also)_
Two GPU.

here is crushdump:
https://dz23a0-my.sharepoint.com/personal/dzon13_ov-office365_site/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fdzon13%5Fov%2Doffice365%5Fsite%2FDocuments%2Fcrashdump%5FDESKTOP%2D66ITIKO%5F2019%2D07%2D30%5F11%2D45%2D16%2Edmp&parent=%2Fpersonal%2Fdzon13%5Fov%2Doffice365%5Fsite%2FDocuments&cid=9da50e7e-58c1-4ffa-811c-49a887bb48af

and logs:
[zanod.log](https://github.com/hyle-team/zano/files/3446770/zanod.log)
[Zano (1).log](https://github.com/hyle-team/zano/files/3446775/Zano.1.log)

> There was similar bug with same error:
> https://jira.hyle.io/browse/ZANO-367

**Comment by cryptozoidberg** [comment]
the crash dump file is not available anymore, issue assumed as fixed.
