### ISSUE TITLE
Try to use libmdbx

### ISSUE THREAD

**Issue by cryptozoidberg** [hyle-team/zano#91]
Need to try to use libmdbx by from https://github.com/leo-yuriev/libmdbx

**Comment by josephnicholas** [comment]
@cryptozoidberg still open? Is this a direct migration from the LMDB code?

**Comment by cryptozoidberg** [comment]
> @cryptozoidberg still open? Is this a direct migration from the LMDB code?

Hi @josephnicholas, I've already implemented support of mdbx in this [branch](https://github.com/hyle-team/zano/tree/libmdbx), but haven't merged it yet to the main workflow, we wanted to be sure that hard fork update done well. It will be included as alternative db in one of upcoming releases.

**Comment by josephnicholas** [comment]
@cryptozoidberg any other task that I can start on?

**Comment by cryptozoidberg** [comment]
> @cryptozoidberg any other task that I can start on?

#71, #75,  #79, #106  actually you can take any problem that you like and try to take care of it.

**Comment by cryptozoidberg** [comment]
@josephnicholas btw, before doing anything my advice is to check this: https://github.com/hyle-team/docs/blob/master/code_style.md

**Comment by cryptozoidberg** [comment]
mdbx support implemented as alternative db engine
