### ISSUE TITLE
Build v1.0.43[c26e56f] crash after launch

### ISSUE THREAD

**Issue by Andreevsky** [hyle-team/zano#92]
Program crash if run on previous build blockchain data (v41).
If delete appdata then build succesfully run and start to sync blockchain.
This happens on windows. On Macos and ubuntu zano run well and start resyncyng blockchain automatically.
[Zanolog.txt](https://github.com/hyle-team/zano/files/3503832/Zanolog.txt)

**Comment by sowle** [comment]
fixed by f6a3fb5

**Comment by Andreevsky** [comment]
v1.0.43[30e967b] fixed
